var chapters = [
  { topic: "chapter", section: "1", title: "Introduction", anchor: "ADMQS001", file: "intro.htm" },
  { topic: "chapter", section: "2", title: "Installing Oracle Database and Creating a Database", anchor: "ADMQS002", file: "install.htm" },
  { topic: "chapter", section: "3", title: "Getting Started with Database Administration", anchor: "ADMQS003", file: "em_manage.htm" },
  { topic: "chapter", section: "4", title: "Configuring the Network Environment", anchor: "ADMQS004", file: "network.htm" },
  { topic: "chapter", section: "5", title: "Managing the Oracle Instance", anchor: "ADMQS005", file: "instance.htm" },
  { topic: "chapter", section: "6", title: "Managing Database Storage Structures", anchor: "ADMQS006", file: "storage.htm" },
  { topic: "chapter", section: "7", title: "Administering User Accounts and Security", anchor: "ADMQS007", file: "users_secure.htm" },
  { topic: "chapter", section: "8", title: "Managing Schema Objects", anchor: "ADMQS008", file: "schema.htm" },
  { topic: "chapter", section: "9", title: "Performing Backup and Recovery", anchor: "ADMQS009", file: "backrest.htm" },
  { topic: "chapter", section: "10", title: "Monitoring and Tuning the Database", anchor: "ADMQS010", file: "montune.htm" },
  { topic: "chapter", section: "11", title: "Investigating, Reporting, and Resolving Problems", anchor: "ADMQS12010", file: "problems.htm" },
  { topic: "chapter", section: "12", title: "Managing Oracle Database Software", anchor: "ADMQS1100", file: "software.htm" },
  { topic: "appendix", section: "A", title: "Administering Oracle Automatic Storage Management", anchor: "ADMQS12100", file: "asm.htm" },
  { } ];
