var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to XStream", anchor: "XSTRM72647", file: "xstrm_intro.htm" },
  { topic: "chapter", section: "2", title: "XStream Concepts", anchor: "XSTRM187", file: "xstrm_cncpt.htm" },
  { topic: "chapter", section: "3", title: "XStream Use Cases", anchor: "XSTRM1488", file: "xstrm_use.htm" },
  { topic: "chapter", section: "4", title: "Configuring XStream", anchor: "XSTRM1496", file: "xstrm_config.htm" },
  { topic: "chapter", section: "5", title: "Managing XStream", anchor: "XSTRM1571", file: "xstrm_man.htm" },
  { topic: "chapter", section: "6", title: "Monitoring XStream", anchor: "XSTRM1437", file: "xstrm_mon.htm" },
  { topic: "chapter", section: "7", title: "Troubleshooting XStream", anchor: "XSTRM1641", file: "xstrm_trouble.htm" },
  { topic: "chapter", section: "8", title: "DBMS_XSTREAM_ADM", anchor: "XSTRM70182", file: "xstrm_xstream_adm.htm" },
  { topic: "chapter", section: "9", title: "DBMS_XSTREAM_AUTH", anchor: "XSTRM72554", file: "xstrm_auth.htm" },
  { topic: "chapter", section: "10", title: "Introduction to the OCI Interface for XStream", anchor: "XSTRM72492", file: "xstrm_oci_intro.htm" },
  { topic: "chapter", section: "11", title: "OCI XStream Functions", anchor: "XSTRM17710", file: "xstrm_oci.htm" },
  { topic: "chapter", section: "12", title: "XStream Static Data Dictionary Views", anchor: "XSTRM72508", file: "xstrm_static_views.htm" },
  { topic: "chapter", section: "13", title: "XStream Dynamic Performance (V$) Views", anchor: "XSTRM72531", file: "xstrm_dp_views.htm" },
  { } ];
