var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle RAC", anchor: "RACAD1111", file: "admcon.htm" },
  { topic: "chapter", section: "2", title: "Administering Storage", anchor: "RACAD703", file: "storage.htm" },
  { topic: "chapter", section: "3", title: "Administering Database Instances and Cluster Databases", anchor: "RACAD900", file: "admin.htm" },
  { topic: "chapter", section: "4", title: "Administering Oracle RAC One Node", anchor: "RACAD7894", file: "onenode.htm" },
  { topic: "chapter", section: "5", title: "Introduction to Automatic Workload Management", anchor: "RACAD076", file: "hafeats.htm" },
  { topic: "chapter", section: "6", title: "Configuring Recovery Manager and Archiving", anchor: "RACAD320", file: "rman.htm" },
  { topic: "chapter", section: "7", title: "Managing Backup and Recovery", anchor: "RACAD059", file: "backup.htm" },
  { topic: "chapter", section: "8", title: "Cloning Oracle RAC to Nodes in a New Cluster", anchor: "RACAD03202", file: "clonerac.htm" },
  { topic: "chapter", section: "9", title: "Using Cloning to Extend Oracle RAC to Nodes in the Same Cluster", anchor: "RACAD007", file: "cloneracwithoui.htm" },
  { topic: "chapter", section: "10", title: "Adding and Deleting Oracle RAC from Nodes on Linux and UNIX Systems", anchor: "RACAD0067", file: "adddelunix.htm" },
  { topic: "chapter", section: "11", title: "Adding and Deleting Oracle RAC from Nodes on Windows Systems", anchor: "RACAD067", file: "adddelwin.htm" },
  { topic: "chapter", section: "12", title: "Design and Deployment Techniques", anchor: "RACAD755", file: "design.htm" },
  { topic: "chapter", section: "13", title: "Monitoring Performance", anchor: "RACAD7395", file: "monitor.htm" },
  { topic: "appendix", section: "A", title: "Server Control Utility Reference", anchor: "RACAD005", file: "srvctladmin.htm" },
  { topic: "appendix", section: "B", title: "Troubleshooting Oracle RAC", anchor: "RACAD025", file: "appsupport.htm" },
  { topic: "appendix", section: "C", title: "Oracle RAC Database (RACDB) Plug-in", anchor: "RACAD8349", file: "racdb.htm" },
  { topic: "appendix", section: "D", title: "Oracle RAC Configuration Audit Tool", anchor: "RACAD8365", file: "racchk.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "RACAD7891", file: "rac_glossary.htm" },
  { } ];
