var chapters = [
  { topic: "chapter", section: "1", title: "Release Notes", anchor: "DFSIG101", file: "relnotes.htm" },
  { topic: "chapter", section: "2", title: "		Architecture and Implementation", anchor: "DFSIG339", file: "database_arch.htm" },
  { topic: "chapter", section: "3", title: "	Oracle Database Installation and Deinstallation", anchor: "DFSIG168", file: "install.htm" },
  { topic: "chapter", section: "4", title: "		Creating and Upgrading a Database", anchor: "DFSIG172", file: "creating_database.htm" },
  { topic: "chapter", section: "5", title: "Administering Oracle Database", anchor: "DFSIG197", file: "admin.htm" },
  { topic: "chapter", section: "6", title: "	Backing Up and Recovering a Database", anchor: "DFSIG212", file: "backup.htm" },
  { topic: "chapter", section: "7", title: "		 Tuning Oracle Database", anchor: "DFSIG224", file: "tuning.htm" },
  { topic: "chapter", section: "8", title: "openUTM Product Set", anchor: "DFSIG228", file: "utm.htm" },
  { topic: "chapter", section: "9", title: "	Oracle Net Services", anchor: "DFSIG247", file: "netv2.htm" },
  { topic: "chapter", section: "10", title: "Oracle Text", anchor: "DFSIG269", file: "initmedia.htm" },
  { topic: "chapter", section: "11", title: "External Procedures", anchor: "DFSIG273", file: "extproc.htm" },
  { topic: "chapter", section: "12", title: "Java in the Database", anchor: "DFSIG422", file: "java.htm" },
  { topic: "chapter", section: "13", title: "	XML", anchor: "DFSIG281", file: "xml.htm" },
  { topic: "chapter", section: "14", title: "Oracle Management Agent", anchor: "DFSIG290", file: "intelliag.htm" },
  { topic: "chapter", section: "15", title: "Oracle Database for Fujitsu BS2000/OSD (SQ Series)", anchor: "DFSIG298", file: "sr2.htm" },
  { topic: "appendix", section: "A", title: "Oracle Error Messages for BS2000/OSD", anchor: "DFSIG310", file: "app_mess.htm" },
  { topic: "appendix", section: "B", title: "Oracle Environment Variables", anchor: "DFSIG311", file: "app_oraenv.htm" },
  { topic: "appendix", section: "C", title: "Initialization Parameters and the Parameter File", anchor: "DFSIG355", file: "app_init.htm" },
  { topic: "appendix", section: "D", title: "Troubleshooting", anchor: "DFSIG366", file: "app_prob.htm" },
  { topic: "appendix", section: "E", title: "File Types and Names Used by Oracle", anchor: "DFSIG377", file: "app_filetype.htm" },
  { } ];
