var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Database", anchor: "CNCPT001", file: "intro.htm" },
  { topic: "chapter", section: "2", title: "Tables and Table Clusters", anchor: "CNCPT010", file: "tablecls.htm" },
  { topic: "chapter", section: "3", title: "Indexes and Index-Organized Tables", anchor: "CNCPT721", file: "indexiot.htm" },
  { topic: "chapter", section: "4", title: "Partitions, Views, and Other Schema Objects", anchor: "CNCPT88858", file: "schemaob.htm" },
  { topic: "chapter", section: "5", title: "Data Integrity", anchor: "CNCPT021", file: "datainte.htm" },
  { topic: "chapter", section: "6", title: "Data Dictionary and Dynamic Performance Views", anchor: "CNCPT002", file: "datadict.htm" },
  { topic: "chapter", section: "7", title: "SQL", anchor: "CNCPT015", file: "sqllangu.htm" },
  { topic: "chapter", section: "8", title: "Server-Side Programming: PL/SQL and Java", anchor: "CNCPT036", file: "srvrside.htm" },
  { topic: "chapter", section: "9", title: "Data Concurrency and Consistency", anchor: "CNCPT020", file: "consist.htm" },
  { topic: "chapter", section: "10", title: "Transactions", anchor: "CNCPT016", file: "transact.htm" },
  { topic: "chapter", section: "11", title: "Physical Storage Structures", anchor: "CNCPT003", file: "physical.htm" },
  { topic: "chapter", section: "12", title: "Logical Storage Structures", anchor: "CNCPT004", file: "logical.htm" },
  { topic: "chapter", section: "13", title: "Oracle Database Instance", anchor: "CNCPT005", file: "startup.htm" },
  { topic: "chapter", section: "14", title: "Memory Architecture", anchor: "CNCPT007", file: "memory.htm" },
  { topic: "chapter", section: "15", title: "Process Architecture", anchor: "CNCPT008", file: "process.htm" },
  { topic: "chapter", section: "16", title: "Application and Networking Architecture", anchor: "CNCPT006", file: "dist_pro.htm" },
  { topic: "chapter", section: "17", title: "Topics for Database Administrators and Developers", anchor: "CNCPT89100", file: "cmntopc.htm" },
  { topic: "chapter", section: "18", title: "Concepts for Database Administrators", anchor: "CNCPT827", file: "cncptdba.htm" },
  { topic: "chapter", section: "19", title: "Concepts for Database Developers", anchor: "CNCPT89121", file: "cncptdev.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "CNCPT89131", file: "glossary.htm" },
  { } ];
