var chapters = [
  { topic: "chapter", section: "1", title: "Overview of Oracle Database Installation", anchor: "LADBI1042", file: "install_overview.htm" },
  { topic: "chapter", section: "2", title: "	Oracle Database Preinstallation Tasks", anchor: "LADBI1085", file: "pre_install.htm" },
  { topic: "chapter", section: "3", title: "Oracle Grid Infrastructure for a Standalone Server", anchor: "LADBI999", file: "oraclerestart.htm" },
  { topic: "chapter", section: "4", title: "Installing Oracle Database", anchor: "LADBI1242", file: "inst_task.htm" },
  { topic: "chapter", section: "5", title: "Oracle Database Postinstallation Tasks", anchor: "LADBI1260", file: "post_inst_task.htm" },
  { topic: "chapter", section: "6", title: "Getting Started with Oracle Database", anchor: "LADBI1308", file: "rev_precon_db.htm" },
  { topic: "chapter", section: "7", title: "Removing Oracle Database Software", anchor: "LADBI1332", file: "remove_oracle_sw.htm" },
  { topic: "appendix", section: "A", title: "Installing and Configuring Oracle Database Using Response Files", anchor: "LADBI1341", file: "app_nonint.htm" },
  { topic: "appendix", section: "B", title: "Cloning an Oracle Home", anchor: "LADBI1362", file: "app_cloning.htm" },
  { topic: "appendix", section: "C", title: "Using NAS Devices", anchor: "LADBI1365", file: "app_nas.htm" },
  { topic: "appendix", section: "D", title: "Optimal Flexible Architecture", anchor: "LADBI1374", file: "appendix_ofa.htm" },
  { topic: "appendix", section: "E", title: "Managing Oracle Database Port Numbers", anchor: "LADBI1400", file: "app_port.htm" },
  { topic: "appendix", section: "F", title: "Configuring Oracle Database Globalization Support", anchor: "LADBI1417", file: "app_glblsupp.htm" },
  { topic: "appendix", section: "G", title: "Troubleshooting", anchor: "LADBI1424", file: "app_ts.htm" },
  { topic: "appendix", section: "H", title: "Frequently Asked Questions About Installation", anchor: "LADBI1443", file: "app_faq.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "LADBI1472", file: "glossary.htm" },
  { } ];
