var chapters = [
  { topic: "chapter", section: "1", title: "OCI: Introduction and Upgrading", anchor: "LNOCI010", file: "oci01int.htm" },
  { topic: "chapter", section: "2", title: "OCI Programming Basics", anchor: "LNOCI020", file: "oci02bas.htm" },
  { topic: "chapter", section: "3", title: "Data Types", anchor: "LNOCI030", file: "oci03typ.htm" },
  { topic: "chapter", section: "4", title: "Using SQL Statements in OCI", anchor: "LNOCI040", file: "oci04sql.htm" },
  { topic: "chapter", section: "5", title: "Binding and Defining in OCI", anchor: "LNOCI050", file: "oci05bnd.htm" },
  { topic: "chapter", section: "6", title: "Describing Schema Metadata", anchor: "LNOCI060", file: "oci06des.htm" },
  { topic: "chapter", section: "7", title: "LOB and BFILE Operations", anchor: "LNOCI070", file: "oci07lob.htm" },
  { topic: "chapter", section: "8", title: "Managing Scalable Platforms", anchor: "LNOCI080", file: "oci08sca.htm" },
  { topic: "chapter", section: "9", title: "																					 OCI Programming Advanced Topics", anchor: "LNOCI090", file: "oci09adv.htm" },
  { topic: "chapter", section: "10", title: "More OCI Advanced Topics", anchor: "LNOCI092", file: "oci10new.htm" },
  { topic: "chapter", section: "11", title: "OCI Object-Relational Programming", anchor: "LNOCI100", file: "oci11obj.htm" },
  { topic: "chapter", section: "12", title: "Object-Relational Data Types in OCI", anchor: "LNOCI110", file: "oci12oty.htm" },
  { topic: "chapter", section: "13", title: "Direct Path Loading", anchor: "LNOCI120", file: "oci13obn.htm" },
  { topic: "chapter", section: "14", title: "Object Advanced Topics in OCI", anchor: "LNOCI130", file: "oci14oca.htm" },
  { topic: "chapter", section: "15", title: "Using the Object Type Translator with OCI", anchor: "LNOCI140", file: "oci15ott.htm" },
  { topic: "chapter", section: "16", title: "OCI Relational Functions", anchor: "LNOCI150", file: "oci16rel.htm" },
  { topic: "chapter", section: "17", title: "More OCI Relational Functions", anchor: "LNOCI160", file: "oci17msc.htm" },
  { topic: "chapter", section: "18", title: "OCI Navigational and Type Functions", anchor: "LNOCI170", file: "oci18nav.htm" },
  { topic: "chapter", section: "19", title: "OCI Data Type Mapping and Manipulation Functions", anchor: "LNOCI180", file: "oci19map.htm" },
  { topic: "chapter", section: "20", title: "OCI Cartridge Functions", anchor: "LNOCI190", file: "oci20ext.htm" },
  { topic: "chapter", section: "21", title: "OCI Any Type and Data Functions", anchor: "LNOCI200", file: "oci21any.htm" },
  { topic: "chapter", section: "22", title: "OCI Globalization Support Functions", anchor: "LNOCI210", file: "oci22glb.htm" },
  { topic: "chapter", section: "23", title: "OCI XML DB Functions", anchor: "LNOCI220", file: "oci23xml.htm" },
  { topic: "appendix", section: "A", title: "Handle and Descriptor Attributes", anchor: "LNOCI250", file: "ociaahan.htm" },
  { topic: "appendix", section: "B", title: "OCI Demonstration Programs", anchor: "LNOCI280", file: "ociabdem.htm" },
  { topic: "appendix", section: "C", title: "OCI Function Server Round-Trips", anchor: "LNOCI300", file: "ociacrou.htm" },
  { topic: "appendix", section: "D", title: "Getting Started with OCI for Windows", anchor: "LNOCI350", file: "ociadwin.htm" },
  { topic: "appendix", section: "E", title: "Deprecated OCI Functions", anchor: "LNOCI18389", file: "ociaedep.htm" },
  { } ];
