var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Large Objects", anchor: "ADLOB001", file: "adlob_intro.htm" },
  { topic: "chapter", section: "2", title: "Working with LOBs", anchor: "ADLOB002", file: "adlob_working.htm" },
  { topic: "chapter", section: "3", title: "Managing LOBs: Database Administration", anchor: "ADLOB45150", file: "adlob_managing.htm" },
  { topic: "chapter", section: "4", title: "Using Oracle SecureFiles LOBs", anchor: "ADLOB4444", file: "adlob_smart.htm" },
  { topic: "chapter", section: "5", title: "Introducing the Oracle Database File System", anchor: "ADLOB45943", file: "adlob_fs.htm" },
  { topic: "chapter", section: "6", title: "DBFS File System Client", anchor: "ADLOB0006", file: "adlob_client.htm" },
  { topic: "chapter", section: "7", title: "DBFS Content API", anchor: "ADLOB007", file: "adlob_cont.htm" },
  { topic: "chapter", section: "8", title: "DBFS SecureFiles Store", anchor: "ADLOB4594", file: "adlob_sfstore.htm" },
  { topic: "chapter", section: "9", title: "DBFS Hierarchical Store", anchor: "ADLOB006", file: "adlob_hierarch.htm" },
  { topic: "chapter", section: "10", title: "Creating a DBFS Store", anchor: "ADLOB0079", file: "adlob_dbstore.htm" },
  { topic: "chapter", section: "11", title: "LOB Storage", anchor: "ADLOB45259", file: "adlob_tables.htm" },
  { topic: "chapter", section: "12", title: "Advanced Design Considerations", anchor: "ADLOB45318", file: "adlob_design.htm" },
  { topic: "chapter", section: "13", title: "Overview of Supplied LOB APIs", anchor: "ADLOB45356", file: "adlob_api_overview.htm" },
  { topic: "chapter", section: "14", title: "Performance Guidelines", anchor: "ADLOB45549", file: "adlob_performance.htm" },
  { topic: "chapter", section: "15", title: "DDL and DML Statements with LOBs", anchor: "ADLOB45560", file: "adlob_ddl.htm" },
  { topic: "chapter", section: "16", title: "SQL Semantics and LOBs", anchor: "ADLOB010", file: "adlob_sql_semantics.htm" },
  { topic: "chapter", section: "17", title: "PL/SQL Semantics for LOBs", anchor: "ADLOB45599", file: "adlob_plsql_semantics.htm" },
  { topic: "chapter", section: "18", title: "Migrating Columns from LONGs to LOBs", anchor: "ADLOB008", file: "adlob_long_lob.htm" },
  { topic: "chapter", section: "19", title: "Operations Specific to Persistent and Temporary LOBs", anchor: "ADLOB45635", file: "adlob_creating.htm" },
  { topic: "chapter", section: "20", title: "Data Interface for Persistent LOBs", anchor: "ADLOB1300", file: "adlob_data_interface.htm" },
  { topic: "chapter", section: "21", title: "LOB APIs for BFILE Operations", anchor: "ADLOB012", file: "adlob_bfile_ops.htm" },
  { topic: "chapter", section: "22", title: "Using LOB APIs", anchor: "ADLOB1400", file: "adlob_lob_ops.htm" },
  { topic: "appendix", section: "A", title: "LOB Demonstration Files", anchor: "ADLOB45913", file: "adlob_demo.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "ADLOB45922", file: "glossary.htm" },
  { } ];
