var chapters = [
  { topic: "chapter", section: "1", title: "Performance Tuning Overview", anchor: "PFGRF025", file: "perf_overview.htm" },
  { topic: "chapter", section: "2", title: "Designing and Developing for Performance", anchor: "PFGRF030", file: "design.htm" },
  { topic: "chapter", section: "3", title: "Performance Improvement Methods", anchor: "PFGRF032", file: "technique.htm" },
  { topic: "chapter", section: "4", title: "Configuring a Database for Performance", anchor: "PFGRF013", file: "build_db.htm" },
  { topic: "chapter", section: "5", title: "Automatic Performance Statistics", anchor: "PFGRF027", file: "autostat.htm" },
  { topic: "chapter", section: "6", title: "Automatic Performance Diagnostics", anchor: "PFGRF026", file: "diag.htm" },
  { topic: "chapter", section: "7", title: "Configuring and Using Memory", anchor: "PFGRF014", file: "memory.htm" },
  { topic: "chapter", section: "8", title: "I/O Configuration and Design", anchor: "PFGRF015", file: "iodesign.htm" },
  { topic: "chapter", section: "9", title: "Managing Operating System Resources", anchor: "PFGRF016", file: "os.htm" },
  { topic: "chapter", section: "10", title: "Instance Tuning Using Performance Views", anchor: "PFGRF024", file: "instance_tune.htm" },
  { topic: "chapter", section: "11", title: "The Query Optimizer", anchor: "PFGRF001", file: "optimops.htm" },
  { topic: "chapter", section: "12", title: "Using EXPLAIN PLAN", anchor: "PFGRF009", file: "ex_plan.htm" },
  { topic: "chapter", section: "13", title: "Managing Optimizer Statistics", anchor: "PFGRF003", file: "stats.htm" },
  { topic: "chapter", section: "14", title: "Using Indexes and Clusters", anchor: "PFGRF004", file: "data_acc.htm" },
  { topic: "chapter", section: "15", title: "Using SQL Plan Management", anchor: "PFGRF007", file: "optplanmgmt.htm" },
  { topic: "chapter", section: "16", title: "SQL Tuning Overview", anchor: "PFGRF006", file: "sql_overview.htm" },
  { topic: "chapter", section: "17", title: "Automatic SQL Tuning", anchor: "PFGRF028", file: "sql_tune.htm" },
  { topic: "chapter", section: "18", title: "SQL Access Advisor", anchor: "PFGRF008", file: "advisor.htm" },
  { topic: "chapter", section: "19", title: "Using Optimizer Hints", anchor: "PFGRF005", file: "hintsref.htm" },
  { topic: "chapter", section: "20", title: "Using Plan Stability", anchor: "PFGRF707", file: "outlines.htm" },
  { topic: "chapter", section: "21", title: "Using Application Tracing Tools", anchor: "PFGRF010", file: "sqltrace.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "PFGRF95019", file: "glossary.htm" },
  { } ];
