var chapters = [
  { topic: "chapter", section: "1", title: "Overview of PL/SQL", anchor: "LNPLS001", file: "overview.htm" },
  { topic: "chapter", section: "2", title: "PL/SQL Language Fundamentals", anchor: "LNPLS002", file: "fundamentals.htm" },
  { topic: "chapter", section: "3", title: "PL/SQL Data Types", anchor: "LNPLS003", file: "datatypes.htm" },
  { topic: "chapter", section: "4", title: "PL/SQL Control Statements", anchor: "LNPLS004", file: "controlstatements.htm" },
  { topic: "chapter", section: "5", title: "PL/SQL Collections and Records", anchor: "LNPLS005", file: "composites.htm" },
  { topic: "chapter", section: "6", title: "PL/SQL Static SQL", anchor: "LNPLS006", file: "static.htm" },
  { topic: "chapter", section: "7", title: "PL/SQL Dynamic SQL", anchor: "LNPLS011", file: "dynamic.htm" },
  { topic: "chapter", section: "8", title: "PL/SQL Subprograms", anchor: "LNPLS008", file: "subprograms.htm" },
  { topic: "chapter", section: "9", title: "PL/SQL Triggers", anchor: "LNPLS020", file: "triggers.htm" },
  { topic: "chapter", section: "10", title: "PL/SQL Packages", anchor: "LNPLS009", file: "packages.htm" },
  { topic: "chapter", section: "11", title: "PL/SQL Error Handling", anchor: "LNPLS007", file: "errors.htm" },
  { topic: "chapter", section: "12", title: "PL/SQL Optimization and Tuning", anchor: "LNPLS012", file: "tuning.htm" },
  { topic: "chapter", section: "13", title: "PL/SQL Language Elements", anchor: "LNPLS013", file: "langelems.htm" },
  { topic: "chapter", section: "14", title: "SQL Statements for Stored PL/SQL Units", anchor: "LNPLS99979", file: "sqlstatements.htm" },
  { topic: "appendix", section: "A", title: "PL/SQL Source Text Wrapping", anchor: "LNPLS016", file: "wrap.htm" },
  { topic: "appendix", section: "B", title: "PL/SQL Name Resolution", anchor: "LNPLS017", file: "nameresolution.htm" },
  { topic: "appendix", section: "C", title: "PL/SQL Program Limits", anchor: "LNPLS018", file: "limits.htm" },
  { topic: "appendix", section: "D", title: "PL/SQL Reserved Words and Keywords", anchor: "LNPLS019", file: "reservewords.htm" },
  { topic: "appendix", section: "E", title: "PL/SQL Predefined Data Types", anchor: "LNPLS2047", file: "predefined.htm" },
  { } ];
