var chapters = [
  { topic: "chapter", section: "1", title: "Data Warehousing Concepts", anchor: "DWHSG001", file: "concept.htm" },
  { topic: "chapter", section: "2", title: "Logical Design in Data Warehouses", anchor: "DWHSG002", file: "logical.htm" },
  { topic: "chapter", section: "3", title: "Physical Design in Data Warehouses", anchor: "DWHSG003", file: "physical.htm" },
  { topic: "chapter", section: "4", title: "Hardware and I/O Considerations in Data Warehouses", anchor: "DWHSG004", file: "hardware.htm" },
  { topic: "chapter", section: "5", title: "Partitioning in Data Warehouses", anchor: "DWHSG005", file: "parpart.htm" },
  { topic: "chapter", section: "6", title: "Parallel Execution in Data Warehouses", anchor: "CHDHDBBI", file: "px.htm" },
  { topic: "chapter", section: "7", title: "Indexes", anchor: "DWHSG006", file: "indexes.htm" },
  { topic: "chapter", section: "8", title: "Integrity Constraints", anchor: "DWHSG007", file: "constra.htm" },
  { topic: "chapter", section: "9", title: "Basic Materialized Views", anchor: "DWHSG008", file: "basicmv.htm" },
  { topic: "chapter", section: "10", title: "Advanced Materialized Views", anchor: "DWHSG009", file: "advmv.htm" },
  { topic: "chapter", section: "11", title: "Dimensions", anchor: "DWHSG010", file: "dimen.htm" },
  { topic: "chapter", section: "12", title: "Overview of Extraction, Transformation, and Loading", anchor: "DWHSG011", file: "ettover.htm" },
  { topic: "chapter", section: "13", title: "Extraction in Data Warehouses", anchor: "DWHSG012", file: "extract.htm" },
  { topic: "chapter", section: "14", title: "Transportation in Data Warehouses", anchor: "DWHSG013", file: "transport.htm" },
  { topic: "chapter", section: "15", title: "Loading and Transformation", anchor: "DWHSG014", file: "transform.htm" },
  { topic: "chapter", section: "16", title: "Maintaining the Data Warehouse", anchor: "DWHSG015", file: "refresh.htm" },
  { topic: "chapter", section: "17", title: "Change Data Capture", anchor: "DWHSG016", file: "cdc.htm" },
  { topic: "chapter", section: "18", title: "Basic Query Rewrite", anchor: "DWHSG018", file: "qrbasic.htm" },
  { topic: "chapter", section: "19", title: "Advanced Query Rewrite", anchor: "DWHSG080", file: "qradv.htm" },
  { topic: "chapter", section: "20", title: "Schema Modeling Techniques", anchor: "DWHSG019", file: "schemas.htm" },
  { topic: "chapter", section: "21", title: "SQL for Aggregation in Data Warehouses", anchor: "DWHSG020", file: "aggreg.htm" },
  { topic: "chapter", section: "22", title: "SQL for Analysis and Reporting", anchor: "DWHSG021", file: "analysis.htm" },
  { topic: "chapter", section: "23", title: "SQL for Modeling", anchor: "DWHSG022", file: "sqlmodel.htm" },
  { topic: "chapter", section: "24", title: "Advanced Business Intelligence Queries", anchor: "DWHSG027", file: "advbi.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "DWHSG8819", file: "glossary.htm" },
  { } ];
