var chapters = [
  { topic: "chapter", section: "1", title: "Introduction", anchor: "g10729", file: "pc_01int.htm" },
  { topic: "chapter", section: "2", title: "Precompiler Concepts", anchor: "g15170", file: "pc_02prc.htm" },
  { topic: "chapter", section: "3", title: "Database Concepts", anchor: "g18485", file: "pc_03dbc.htm" },
  { topic: "chapter", section: "4", title: "Datatypes and Host Variables", anchor: "g52211", file: "pc_04dat.htm" },
  { topic: "chapter", section: "5", title: "Advanced Topics", anchor: "g462796", file: "pc_05adv.htm" },
  { topic: "chapter", section: "6", title: "Embedded SQL", anchor: "g19457", file: "pc_06sql.htm" },
  { topic: "chapter", section: "7", title: "		Embedded PL/SQL", anchor: "g27962", file: "pc_07pls.htm" },
  { topic: "chapter", section: "8", title: "Host Arrays", anchor: "g20885", file: "pc_08arr.htm" },
  { topic: "chapter", section: "9", title: "Handling Runtime Errors", anchor: "g35612", file: "pc_09err.htm" },
  { topic: "chapter", section: "10", title: "	Precompiler Options", anchor: "g30455", file: "pc_10opt.htm" },
  { topic: "chapter", section: "11", title: "Multithreaded Applications", anchor: "g1021123", file: "pc_11thr.htm" },
  { topic: "chapter", section: "12", title: "C++ Applications", anchor: "g12549", file: "pc_12cpl.htm" },
  { topic: "chapter", section: "13", title: "Oracle Dynamic SQL", anchor: "LNPCC012", file: "pc_13dyn.htm" },
  { topic: "chapter", section: "14", title: "	ANSI Dynamic SQL", anchor: "i1011699", file: "pc_14ady.htm" },
  { topic: "chapter", section: "15", title: "Oracle Dynamic SQL: Method 4", anchor: "LNPCC015", file: "pc_15ody.htm" },
  { topic: "chapter", section: "16", title: "LOBs", anchor: "LNPCC016", file: "pc_16lob.htm" },
  { topic: "chapter", section: "17", title: "Objects", anchor: "g480794", file: "pc_17obj.htm" },
  { topic: "chapter", section: "18", title: "Collections", anchor: "g1023189", file: "pc_18col.htm" },
  { topic: "chapter", section: "19", title: "The Object Type Translator", anchor: "g464850", file: "pc_19ott.htm" },
  { topic: "chapter", section: "20", title: "User Exits", anchor: "LNPCC019", file: "pc_20exi.htm" },
  { topic: "appendix", section: "A", title: "	New Features", anchor: "CJAHCJGA", file: "pc_aanew.htm" },
  { topic: "appendix", section: "B", title: "	Reserved Words, Keywords, and Namespaces", anchor: "CJACFAAC", file: "pc_abres.htm" },
  { topic: "appendix", section: "C", title: "	Performance Tuning", anchor: "LNPCC023", file: "pc_actun.htm" },
  { topic: "appendix", section: "D", title: "Syntactic and Semantic Checking", anchor: "LNPCC024", file: "pc_adchk.htm" },
  { topic: "appendix", section: "E", title: "	System-Specific References", anchor: "BACHEAAI", file: "pc_aeops.htm" },
  { topic: "appendix", section: "F", title: "	Embedded SQL Statements and Directives", anchor: "LNPCC020", file: "pc_afemb.htm" },
  { topic: "appendix", section: "G", title: "Sample Programs", anchor: "", file: "pc_agsmp.htm" },
  { topic: "appendix", section: "H", title: "Integrating Pro*C/C++ into Microsoft Visual Studio .NET 2002/2003", anchor: "", file: "pc_ahintegrat.htm" },
  { } ];
