var chapters = [
  { topic: "chapter", section: "1", title: "Installation Overview", anchor: "OIDBI912", file: "overview.htm" },
  { topic: "chapter", section: "2", title: "Preinstallation Tasks", anchor: "OIDBI952", file: "pre_inst.htm" },
  { topic: "chapter", section: "3", title: "Installation Tasks", anchor: "OIDBI1021", file: "install.htm" },
  { topic: "chapter", section: "4", title: "Postinstallation Tasks", anchor: "OIDBI1036", file: "postinst.htm" },
  { topic: "chapter", section: "5", title: "Getting Started with Oracle Database", anchor: "OIDBI1139", file: "review.htm" },
  { topic: "chapter", section: "6", title: "Removing Oracle Software", anchor: "OIDBI1162", file: "removing.htm" },
  { topic: "appendix", section: "A", title: "Oracle Database 64-Bit Feature", anchor: "OIDBI1172", file: "a_64_bit.htm" },
  { topic: "appendix", section: "B", title: "Noninteractive Installation and Configuration", anchor: "OIDBI1178", file: "a_nonint.htm" },
  { topic: "appendix", section: "C", title: "Installing, Configuring, and Running Enterprise Manager Agent", anchor: "OIDBI1236", file: "a_opflex.htm" },
  { topic: "appendix", section: "D", title: "Managing Oracle Database Port Numbers", anchor: "OIDBI1256", file: "app_port.htm" },
  { topic: "appendix", section: "E", title: "Configuring Oracle Database Globalization Support", anchor: "OIDBI1262", file: "app_gblsupp.htm" },
  { topic: "appendix", section: "F", title: "Troubleshooting", anchor: "OIDBI1264", file: "a_trblsh.htm" },
  { topic: "appendix", section: "G", title: "Apache Server Configuration", anchor: "OIDBI1276", file: "a_apache.htm" },
  { topic: "appendix", section: "H", title: "Identifying Listener Processes", anchor: "OIDBI1328", file: "a_lsnr_code.htm" },
  { } ];
