var chapters = [
  { topic: "chapter", section: "1", title: "Introducing Oracle Database Vault", anchor: "DVADM001", file: "dvintro.htm" },
  { topic: "chapter", section: "2", title: "What to Expect After You Install Oracle\u00A0Database Vault", anchor: "DVADM018", file: "dv_impact.htm" },
  { topic: "chapter", section: "3", title: "Getting Started with Oracle Database Vault", anchor: "DVADM002", file: "getting_started.htm" },
  { topic: "chapter", section: "4", title: "Configuring Realms", anchor: "DVADM003", file: "cfrealms.htm" },
  { topic: "chapter", section: "5", title: "Configuring Rule Sets", anchor: "DVADM006", file: "cfrulset.htm" },
  { topic: "chapter", section: "6", title: "Configuring Command Rules", anchor: "DVADM005", file: "cfcmdaut.htm" },
  { topic: "chapter", section: "7", title: "Configuring Factors", anchor: "DVADM004", file: "cfgfact.htm" },
  { topic: "chapter", section: "8", title: "Configuring Secure Application Roles for\u00A0Oracle Database Vault", anchor: "DVADM007", file: "cfseappr.htm" },
  { topic: "chapter", section: "9", title: "Integrating Oracle Database Vault with Other\u00A0Oracle Products", anchor: "DVADM008", file: "dv_ols.htm" },
  { topic: "chapter", section: "10", title: "DBA Operations in an Oracle Database Vault Environment", anchor: "DVADM71122", file: "dba.htm" },
  { topic: "chapter", section: "11", title: "Oracle Database Vault Objects", anchor: "DVADM013", file: "db_objects.htm" },
  { topic: "chapter", section: "12", title: "Using the DBMS_MACADM Package", anchor: "DVADM016", file: "apis_dbms_macadm.htm" },
  { topic: "chapter", section: "13", title: "Using the DBMS_MACSEC_ROLES Package", anchor: "DVADM099", file: "apis_macsec_roles.htm" },
  { topic: "chapter", section: "14", title: "Using the DBMS_MACUTL Package", anchor: "DVADM020", file: "apis_dbms_macutl.htm" },
  { topic: "chapter", section: "15", title: "Using the Oracle Database Vault PL/SQL\u00A0Interfaces", anchor: "DVADM014", file: "plsql_interfaces.htm" },
  { topic: "chapter", section: "16", title: "Oracle Database Vault Data Dictionary Views", anchor: "DVADM70378", file: "views.htm" },
  { topic: "chapter", section: "17", title: "Monitoring Oracle Database Vault", anchor: "DVADM010", file: "monitoring.htm" },
  { topic: "chapter", section: "18", title: "Oracle Database Vault Reports", anchor: "DVADM009", file: "reports.htm" },
  { topic: "appendix", section: "A", title: "Auditing Oracle Database Vault", anchor: "DVADM011", file: "audplcy.htm" },
  { topic: "appendix", section: "B", title: "Disabling and Enabling Oracle\u00A0Database\u00A0Vault", anchor: "DVADM012", file: "dvdisabl.htm" },
  { topic: "appendix", section: "C", title: "Postinstallation Oracle\u00A0Database Vault Procedures", anchor: "DVADM022", file: "dvca.htm" },
  { topic: "appendix", section: "D", title: "Oracle Database Vault Security Guidelines", anchor: "DVADM019", file: "guidelines.htm" },
  { topic: "appendix", section: "E", title: "Troubleshooting Oracle Database Vault", anchor: "DVADM017", file: "troubleshooting.htm" },
  { } ];
