var chapters = [
  { topic: "chapter", section: "1", title: "Quick Start", anchor: "HTMDB01000", file: "start.htm" },
  { topic: "chapter", section: "2", title: "Running a Demonstration Application", anchor: "HTMDB02000", file: "demo.htm" },
  { topic: "chapter", section: "3", title: "Application Builder Concepts", anchor: "HTMDB03000", file: "concept.htm" },
  { topic: "chapter", section: "4", title: "Using Application Builder", anchor: "HTMDB04000", file: "bldr.htm" },
  { topic: "chapter", section: "5", title: "Working with Application Pages", anchor: "HTMDB25097", file: "bldr_pgs.htm" },
  { topic: "chapter", section: "6", title: "Building an Application", anchor: "HTMDB05001", file: "bldapp.htm" },
  { topic: "chapter", section: "7", title: "Adding Application Components", anchor: "HTMDB25344", file: "app_comp.htm" },
  { topic: "chapter", section: "8", title: "Adding Navigation", anchor: "HTMDB07001", file: "nav.htm" },
  { topic: "chapter", section: "9", title: "Controlling Page Layout", anchor: "HTMDB25564", file: "ui.htm" },
  { topic: "chapter", section: "10", title: "Managing Themes and Templates", anchor: "HTMDB25593", file: "themes.htm" },
  { topic: "chapter", section: "11", title: "Managing User Interface Defaults", anchor: "HTMDB09001", file: "ui_default.htm" },
  { topic: "chapter", section: "12", title: "Debugging an Application", anchor: "HTMDB10000", file: "debug.htm" },
  { topic: "chapter", section: "13", title: "Managing Application Security", anchor: "HTMDB12000", file: "sec.htm" },
  { topic: "chapter", section: "14", title: "Deploying an Application", anchor: "HTMDB11000", file: "deploy.htm" },
  { topic: "chapter", section: "15", title: "Advanced Programming Techniques", anchor: "HTMDB13000", file: "advnc.htm" },
  { topic: "chapter", section: "16", title: "Managing Application Globalization", anchor: "HTMDB14000", file: "global.htm" },
  { topic: "appendix", section: "A", title: "Available Conditions", anchor: "HTMDB25942", file: "condition.htm" },
  { topic: "appendix", section: "B", title: "Privileges Granted to PUBLIC", anchor: "HTMDB25944", file: "priv_public.htm" },
  { } ];
