var chapters = [
  { topic: "chapter", section: "1", title: "Getting Started with Oracle Database Gateway", anchor: "IVACW110", file: "gettingstarted.htm" },
  { topic: "chapter", section: "2", title: "Configuring Access to VSAM Data", anchor: "IVACW120", file: "vsamdata_access.htm" },
  { topic: "chapter", section: "3", title: "Installing Oracle Database Gateway for VSAM", anchor: "IVACW179", file: "inst_tgw_vsam.htm" },
  { topic: "chapter", section: "4", title: "Configuring Oracle Database Gateway for VSAM", anchor: "IVACW208", file: "conf_tgw_vsam.htm" },
  { topic: "chapter", section: "5", title: "Configuring Access to IMS Data", anchor: "IVACW245", file: "imsdata_access.htm" },
  { topic: "chapter", section: "6", title: "Installing Oracle Database Gateway for IMS", anchor: "IVACW287", file: "inst_tgw_ims.htm" },
  { topic: "chapter", section: "7", title: "Configuring Oracle Database Gateway for IMS", anchor: "IVACW316", file: "conf_tgw_ims.htm" },
  { topic: "chapter", section: "8", title: "Configuring Access to Adabas Data", anchor: "IVACW353", file: "adabasdata_access.htm" },
  { topic: "chapter", section: "9", title: "Installing Oracle Database Gateway for Adabas", anchor: "IVACW365", file: "inst_tgw_adabas.htm" },
  { topic: "chapter", section: "10", title: "Configuring Oracle Database Gateway for Adabas", anchor: "IVACW394", file: "conf_tgw_adabas.htm" },
  { topic: "chapter", section: "11", title: "Installing Oracle Studio for IMS, VSAM, and Adabas Gateways", anchor: "IVACW427", file: "inst_studio.htm" },
  { topic: "chapter", section: "12", title: "Working with the Oracle Studio for IMS, VSAM, and Adabas Gateways Workbench", anchor: "IVACW433", file: "studio_workbench.htm" },
  { topic: "chapter", section: "13", title: "Configuring Oracle Connect through Oracle Studio for IMS, VSAM, and Adabas Gateways", anchor: "IVACW478", file: "connectconfiguration.htm" },
  { topic: "chapter", section: "14", title: "Managing Security for Oracle Connect for IMS, VSAM, and Adabas Gateways", anchor: "IVACW546", file: "connectsecurity.htm" },
  { topic: "appendix", section: "A", title: "Initialization Parameters", anchor: "IVACW594", file: "hs_ini_para.htm" },
  { topic: "appendix", section: "B", title: "Using Response Files for Non-Interactive Installation", anchor: "IVACW581", file: "responsefiles.htm" },
  { topic: "appendix", section: "C", title: "Oracle Database Gateway Troubleshooting", anchor: "IVACW620", file: "oraclegw_troubleshooting.htm" },
  { } ];
