var chapters = [
  { topic: "chapter", section: "1", title: "Overview of Installation and Configuration Architecture", anchor: "WBINS01000", file: "overview.htm" },
  { topic: "chapter", section: "2", title: "Installing Oracle Warehouse Builder on the Server", anchor: "WBINS02000", file: "install.htm" },
  { topic: "chapter", section: "3", title: "Configuring Oracle Warehouse Builder for Windows", anchor: "WBINS03000", file: "setup_windows.htm" },
  { topic: "chapter", section: "4", title: "Configuring Oracle Warehouse Builder for Linux", anchor: "WBINS04000", file: "setup_linux.htm" },
  { topic: "chapter", section: "5", title: "Uninstalling Oracle Warehouse Builder", anchor: "WBINS06000", file: "uninstall.htm" },
  { topic: "chapter", section: "6", title: "Moving to Oracle Warehouse Builder 11.2 from Earlier Releases", anchor: "WBINS07000", file: "migrate.htm" },
  { topic: "chapter", section: "7", title: "Configuring Repository Browser, Control Center Agent, and Other Components", anchor: "WBINS08000", file: "components.htm" },
  { topic: "chapter", section: "8", title: "Managing Configurations", anchor: "WBINS13000", file: "multi_design_mgmt.htm" },
  { topic: "chapter", section: "9", title: "Managing the Control Center and Repository", anchor: "WBINS26382", file: "control_ctr_mgmt.htm" },
  { topic: "chapter", section: "10", title: "Managing the Control Center Agent", anchor: "WBINS09000", file: "runtime_mgmt.htm" },
  { topic: "chapter", section: "11", title: "Using Snapshots to Manage Metadata", anchor: "WBINS10000", file: "content_mgmt.htm" },
  { topic: "chapter", section: "12", title: "Importing, Exporting, and Upgrading Metadata", anchor: "WBINS12000", file: "change_mgmt.htm" },
  { topic: "chapter", section: "13", title: "Managing Security", anchor: "WBINS15000", file: "security_mgmt.htm" },
  { topic: "appendix", section: "A", title: "Troubleshooting the Installation and Setup", anchor: "WBINS16307", file: "appendix_troubleshooting.htm" },
  { } ];
