var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Real Application Testing", anchor: "RATUG101", file: "rat_intro.htm" },
  { topic: "chapter", section: "2", title: "Introduction to SQL Performance Analyzer", anchor: "RATUG166", file: "spa_intro.htm" },
  { topic: "chapter", section: "3", title: "Creating an Analysis Task", anchor: "RATUG175", file: "spa_task.htm" },
  { topic: "chapter", section: "4", title: "Creating a Pre-Change SQL Trial", anchor: "RATUG180", file: "spa_pre_change.htm" },
  { topic: "chapter", section: "5", title: "Creating a Post-Change SQL Trial", anchor: "RATUG183", file: "spa_post_change.htm" },
  { topic: "chapter", section: "6", title: "Comparing SQL Trials", anchor: "RATUG186", file: "spa_analyze.htm" },
  { topic: "chapter", section: "7", title: "Testing a Database Upgrade", anchor: "RATUG210", file: "spa_upgrade.htm" },
  { topic: "chapter", section: "8", title: "Introduction to Database Replay", anchor: "RATUG104", file: "dbr_intro.htm" },
  { topic: "chapter", section: "9", title: "Capturing a Database Workload", anchor: "RATUG109", file: "dbr_capture.htm" },
  { topic: "chapter", section: "10", title: "Preprocessing a Database Workload", anchor: "RATUG128", file: "dbr_preprocess.htm" },
  { topic: "chapter", section: "11", title: "Replaying a Database Workload", anchor: "RATUG131", file: "dbr_replay.htm" },
  { topic: "chapter", section: "12", title: "Analyzing Captured and Replayed Workloads", anchor: "RATUG159", file: "dbr_analyze.htm" },
  { topic: "chapter", section: "13", title: "Using Consolidated Database Replay", anchor: "RATUG4080", file: "dbr_consolidated.htm" },
  { topic: "chapter", section: "14", title: "Application Data Models", anchor: "RATUG4045", file: "tdm_data_disc_modeling.htm" },
  { topic: "chapter", section: "15", title: "Data Subsetting", anchor: "RATUG4052", file: "tdm_subsetting.htm" },
  { topic: "chapter", section: "16", title: "Masking Sensitive Data", anchor: "RATUG04000", file: "tdm_data_masking.htm" },
  { } ];
