var chapters = [
  { topic: "chapter", section: "1", title: "Spatial Concepts", anchor: "SPATL010", file: "sdo_intro.htm" },
  { topic: "chapter", section: "2", title: "Spatial Data Types and Metadata", anchor: "SPATL020", file: "sdo_objrelschema.htm" },
  { topic: "chapter", section: "3", title: "SQL Multimedia Type Support", anchor: "SPATL025", file: "sdo_sql_mm.htm" },
  { topic: "chapter", section: "4", title: "Loading Spatial Data", anchor: "SPATL030", file: "sdo_objload.htm" },
  { topic: "chapter", section: "5", title: "Indexing and Querying Spatial Data", anchor: "SPATL040", file: "sdo_index_query.htm" },
  { topic: "chapter", section: "6", title: "Coordinate Systems (Spatial Reference Systems)", anchor: "SPATL050", file: "sdo_cs_concepts.htm" },
  { topic: "chapter", section: "7", title: "Linear Referencing System", anchor: "SPATL060", file: "sdo_lrs_concepts.htm" },
  { topic: "chapter", section: "8", title: "Spatial Analysis and Mining", anchor: "SPATL070", file: "sdo_sam_concepts.htm" },
  { topic: "chapter", section: "9", title: "Extending Spatial Indexing Capabilities", anchor: "SPATL080", file: "sdo_exten.htm" },
  { topic: "chapter", section: "10", title: "Introduction to Spatial Web Services", anchor: "SPATL044", file: "sdo_webserv_intro.htm" },
  { topic: "chapter", section: "11", title: "Geocoding Address Data", anchor: "SPATL045", file: "sdo_geocode_concepts.htm" },
  { topic: "chapter", section: "12", title: "Business Directory (Yellow Pages) Support", anchor: "SPATL400", file: "sdo_yp.htm" },
  { topic: "chapter", section: "13", title: "Routing Engine", anchor: "SPATL350", file: "sdo_route_server.htm" },
  { topic: "chapter", section: "14", title: "OpenLS Support", anchor: "SPATL410", file: "sdo_openls.htm" },
  { topic: "chapter", section: "15", title: "Web Feature Service (WFS) Support", anchor: "SPATL420", file: "sdo_wfs.htm" },
  { topic: "chapter", section: "16", title: "Catalog Services for the Web (CSW) Support", anchor: "SPATL425", file: "sdo_csw.htm" },
  { topic: "chapter", section: "17", title: "Security Considerations for Spatial Web Services", anchor: "SPATL430", file: "sdo_ws_security.htm" },
  { topic: "chapter", section: "18", title: "SQL Statements for Indexing Spatial Data", anchor: "SPATL090", file: "sdo_objindex.htm" },
  { topic: "chapter", section: "19", title: "Spatial Operators", anchor: "SPATL110", file: "sdo_operat.htm" },
  { topic: "chapter", section: "20", title: "Spatial Aggregate Functions", anchor: "SPATL130", file: "sdo_aggr.htm" },
  { topic: "chapter", section: "21", title: "SDO_CS Package (Coordinate System Transformation)", anchor: "SPATL140", file: "sdo_cs_ref.htm" },
  { topic: "chapter", section: "22", title: "SDO_CSW_PROCESS Package (CSW Processing)", anchor: "SPATL142", file: "sdo_csw_process_ref.htm" },
  { topic: "chapter", section: "23", title: "SDO_GCDR Package (Geocoding)", anchor: "SPATL145", file: "sdo_geocode_ref.htm" },
  { topic: "chapter", section: "24", title: "SDO_GEOM Package (Geometry)", anchor: "SPATL120", file: "sdo_objgeom.htm" },
  { topic: "chapter", section: "25", title: "SDO_LRS Package (Linear Referencing System)", anchor: "SPATL150", file: "sdo_lrs_ref.htm" },
  { topic: "chapter", section: "26", title: "SDO_MIGRATE Package (Upgrading)", anchor: "SPATL160", file: "sdo_objmigr.htm" },
  { topic: "chapter", section: "27", title: "SDO_OLS Package (OpenLS)", anchor: "SPATL146", file: "sdo_ols_ref.htm" },
  { topic: "chapter", section: "28", title: "SDO_PC_PKG Package (Point Clouds)", anchor: "SPATL172", file: "sdo_pc_pkg_ref.htm" },
  { topic: "chapter", section: "29", title: "SDO_SAM Package (Spatial Analysis and Mining)", anchor: "SPATL190", file: "sdo_sam_ref.htm" },
  { topic: "chapter", section: "30", title: "SDO_TIN_PKG Package (TINs)", anchor: "SPATL171", file: "sdo_tin_pkg_ref.htm" },
  { topic: "chapter", section: "31", title: "SDO_TUNE Package (Tuning)", anchor: "SPATL170", file: "sdo_objtune.htm" },
  { topic: "chapter", section: "32", title: "SDO_UTIL Package (Utility)", anchor: "SPATL180", file: "sdo_util.htm" },
  { topic: "chapter", section: "33", title: "SDO_WFS_LOCK Package (WFS)", anchor: "SPATL147", file: "sdo_wfs_lock_ref.htm" },
  { topic: "chapter", section: "34", title: "SDO_WFS_PROCESS Package (WFS Processing)", anchor: "SPATL148", file: "sdo_wfs_process_ref.htm" },
  { topic: "appendix", section: "A", title: "Installation, Migration, Compatibility, and Upgrade", anchor: "SPATL320", file: "sdo_migrat.htm" },
  { topic: "appendix", section: "B", title: "Oracle Locator", anchor: "SPATL340", file: "sdo_locator.htm" },
  { topic: "appendix", section: "C", title: "Complex Spatial Queries: Examples", anchor: "SPATL1277", file: "sdo_complex_queries.htm" },
  { topic: "appendix", section: "D", title: "Loading ESRI Shapefiles into Spatial", anchor: "SPATL1427", file: "sdo_shapefile_converter.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "SPATL1287", file: "glossary.htm" },
  { } ];
