var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Label Security", anchor: "OLSAG001", file: "intro.htm" },
  { topic: "chapter", section: "2", title: "Understanding Data Labels and User Labels", anchor: "OLSAG007", file: "labels.htm" },
  { topic: "chapter", section: "3", title: "Understanding Access Controls and Privileges", anchor: "OLSAG013", file: "accpriv.htm" },
  { topic: "chapter", section: "4", title: "Getting Started with Oracle Label Security", anchor: "OLSAG3096", file: "getstrtd.htm" },
  { topic: "chapter", section: "5", title: "Working with Labeled Data", anchor: "OLSAG019", file: "worklabel.htm" },
  { topic: "chapter", section: "6", title: "Oracle Label Security Using Oracle\u00A0Internet\u00A0Directory", anchor: "OLSAG026", file: "olsoid.htm" },
  { topic: "chapter", section: "7", title: "Creating an Oracle Label Security Policy", anchor: "OLSAG040", file: "creatpol.htm" },
  { topic: "chapter", section: "8", title: "Administering User Labels and Privileges", anchor: "OLSAG047", file: "admpriv.htm" },
  { topic: "chapter", section: "9", title: "Implementing Policy Enforcement Options and Labeling Functions", anchor: "OLSAG055", file: "enforce.htm" },
  { topic: "chapter", section: "10", title: "Applying Policies to Tables and Schemas", anchor: "OLSAG062", file: "admpolcy.htm" },
  { topic: "chapter", section: "11", title: "Administering and Using Trusted Stored Program Units", anchor: "OLSAG068", file: "storproc.htm" },
  { topic: "chapter", section: "12", title: "Auditing Under Oracle Label Security", anchor: "OLSAG073", file: "audit.htm" },
  { topic: "chapter", section: "13", title: "Using Oracle Label Security with a Distributed Database", anchor: "OLSAG080", file: "multiple.htm" },
  { topic: "chapter", section: "14", title: "	 Performing DBA Functions Under Oracle Label Security", anchor: "OLSAG3416", file: "utilities.htm" },
  { topic: "chapter", section: "15", title: "Releasability Using Inverse Groups", anchor: "OLSAG094", file: "releas.htm" },
  { topic: "appendix", section: "A", title: "Advanced Topics in Oracle Label Security", anchor: "OLSAG104", file: "appxa.htm" },
  { topic: "appendix", section: "B", title: "Command-line Tools for Label Security Using Oracle Internet Directory", anchor: "OLSAG108", file: "appxb.htm" },
  { topic: "appendix", section: "C", title: "Oracle Label Security in an Oracle RAC Environment", anchor: "OLSAG3607", file: "appxd.htm" },
  { topic: "appendix", section: "D", title: "Frequently Asked Questions on Oracle Label Security", anchor: "OLSAG3611", file: "faq.htm" },
  { topic: "appendix", section: "E", title: "Reference", anchor: "OLSAG113", file: "appxc.htm" },
  { } ];
