var chapters = [
  { topic: "chapter", section: "1", title: "What's New in Oracle Warehouse Builder", anchor: "WBCON4378", file: "whatsnew.htm" },
  { topic: "chapter", section: "2", title: "Introduction to Oracle Warehouse Builder", anchor: "WBCON4422", file: "intro.htm" },
  { topic: "chapter", section: "3", title: "User Interface Tour", anchor: "WBCON4439", file: "uitour.htm" },
  { topic: "chapter", section: "4", title: "Data Access and Movement", anchor: "WBCON4474", file: "sourcetargs.htm" },
  { topic: "chapter", section: "5", title: "Data Objects", anchor: "WBCON4490", file: "dataobjects.htm" },
  { topic: "chapter", section: "6", title: "Data Transformation", anchor: "WBCON4591", file: "datatransform.htm" },
  { topic: "chapter", section: "7", title: "Dependency and Change Management", anchor: "WBCON4602", file: "metadatamgt.htm" },
  { topic: "chapter", section: "8", title: "Data Quality Management", anchor: "WBCON4640", file: "dataquality.htm" },
  { topic: "chapter", section: "9", title: "Deployment and Execution", anchor: "WBCON4656", file: "deployexec.htm" },
  { topic: "chapter", section: "10", title: "Scripting and Automation", anchor: "WBCON4696", file: "scripting.htm" },
  { topic: "appendix", section: "A", title: "Oracle Warehouse Builder Design Center and Runtime Preferences", anchor: "WBCON4702", file: "apx_prefs.htm" },
  { topic: "appendix", section: "B", title: "Object Editors", anchor: "WBCON4725", file: "apx_editors.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "WBCON4740", file: "glossary.htm" },
  { } ];
