var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Universal Installer", anchor: "OUICG101", file: "oui1_introduction.htm" },
  { topic: "chapter", section: "2", title: "Managing Oracle Homes", anchor: "CJAGCIAC", file: "oui2_manage_oracle_homes.htm" },
  { topic: "chapter", section: "3", title: "Customizing and Creating Response Files", anchor: "CHDDDIHD", file: "oui3_response_files.htm" },
  { topic: "chapter", section: "4", title: "Installing Products", anchor: "BABGCJJF", file: "oui4_product_install.htm" },
  { topic: "chapter", section: "5", title: "Installing Cluster Environments", anchor: "BABJBJDC", file: "oui5_cluster_environment.htm" },
  { topic: "chapter", section: "6", title: "Cloning Oracle Software", anchor: "OUICG294", file: "oui6_cloning.htm" },
  { topic: "chapter", section: "7", title: "Patching Oracle Software with OPatch", anchor: "CEGCJGJD", file: "oui7_opatch.htm" },
  { topic: "chapter", section: "8", title: "Oracle Internationalization and Translation", anchor: "CACGABDD", file: "oui8_internationalization.htm" },
  { topic: "appendix", section: "A", title: "Frequently Asked Questions", anchor: "CHDBDFIF", file: "a_oui_appendix.htm" },
  { topic: "appendix", section: "B", title: "Troubleshooting and Debugging Oracle Universal Installer", anchor: "CHDBDFIF1", file: "b_oui_appendix.htm" },
  { topic: "appendix", section: "C", title: "Understanding Oracle Universal Installer Commands", anchor: "OUICG378", file: "c_oui_appendix.htm" },
  { topic: "appendix", section: "D", title: "Sample Files", anchor: "OUICG381", file: "d_oui_appendix.htm" },
  { topic: "appendix", section: "E", title: "Error Messages and Solutions", anchor: "OUICG386", file: "e_oui_appendix.htm" },
  { } ];
