var chapters = [
  { topic: "chapter", section: "1", title: "Getting Started with Database Administration", anchor: "ADMIN001", file: "dba.htm" },
  { topic: "chapter", section: "2", title: "Creating and Configuring an Oracle Database", anchor: "ADMIN002", file: "create.htm" },
  { topic: "chapter", section: "3", title: "Starting Up and Shutting Down", anchor: "ADMIN004", file: "start.htm" },
  { topic: "chapter", section: "4", title: "Configuring Automatic Restart of an Oracle Database", anchor: "ADMIN12708", file: "restart.htm" },
  { topic: "chapter", section: "5", title: "Managing Processes", anchor: "ADMIN11000", file: "manproc.htm" },
  { topic: "chapter", section: "6", title: "Managing Memory", anchor: "ADMIN00207", file: "memory.htm" },
  { topic: "chapter", section: "7", title: "Managing Users and Securing the Database", anchor: "ADMIN023", file: "secure.htm" },
  { topic: "chapter", section: "8", title: "Monitoring Database Operations", anchor: "ADMIN005", file: "monitoring.htm" },
  { topic: "chapter", section: "9", title: "Managing Diagnostic Data", anchor: "ADMIN11007", file: "diag.htm" },
  { topic: "chapter", section: "10", title: "Managing Oracle Enterprise Manager Database Control", anchor: "ADMIN13401", file: "dbcontrol.htm" },
  { topic: "chapter", section: "11", title: "Managing Control Files", anchor: "ADMIN006", file: "control.htm" },
  { topic: "chapter", section: "12", title: "Managing the Redo Log", anchor: "ADMIN007", file: "onlineredo.htm" },
  { topic: "chapter", section: "13", title: "Managing Archived Redo Logs", anchor: "ADMIN008", file: "archredo.htm" },
  { topic: "chapter", section: "14", title: "Managing Tablespaces", anchor: "ADMIN011", file: "tspaces.htm" },
  { topic: "chapter", section: "15", title: "Managing Data Files and Temp Files", anchor: "ADMIN012", file: "dfiles.htm" },
  { topic: "chapter", section: "16", title: "Managing Undo", anchor: "ADMIN013", file: "undo.htm" },
  { topic: "chapter", section: "17", title: "Using Oracle Managed Files", anchor: "ADMIN003", file: "omf.htm" },
  { topic: "chapter", section: "18", title: "Managing Schema Objects", anchor: "ADMIN021", file: "general.htm" },
  { topic: "chapter", section: "19", title: "Managing Space for Schema Objects", anchor: "ADMIN014", file: "schema.htm" },
  { topic: "chapter", section: "20", title: "Managing Tables", anchor: "ADMIN015", file: "tables.htm" },
  { topic: "chapter", section: "21", title: "Managing Indexes", anchor: "ADMIN016", file: "indexes.htm" },
  { topic: "chapter", section: "22", title: "Managing Clusters", anchor: "ADMIN018", file: "clustrs.htm" },
  { topic: "chapter", section: "23", title: "Managing Hash Clusters", anchor: "ADMIN019", file: "hash.htm" },
  { topic: "chapter", section: "24", title: "Managing Views, Sequences, and Synonyms", anchor: "ADMIN020", file: "views.htm" },
  { topic: "chapter", section: "25", title: "Repairing Corrupted Data", anchor: "ADMIN022", file: "repair.htm" },
  { topic: "chapter", section: "26", title: "Managing Automated Database Maintenance Tasks", anchor: "ADMIN0235", file: "tasks.htm" },
  { topic: "chapter", section: "27", title: "Managing Resources with Oracle Database Resource Manager", anchor: "ADMIN027", file: "dbrm.htm" },
  { topic: "chapter", section: "28", title: "Oracle Scheduler Concepts", anchor: "ADMIN033", file: "schedover.htm" },
  { topic: "chapter", section: "29", title: "Scheduling Jobs with Oracle Scheduler", anchor: "ADMIN034", file: "scheduse.htm" },
  { topic: "chapter", section: "30", title: "Administering Oracle Scheduler", anchor: "ADMIN035", file: "schedadmin.htm" },
  { topic: "chapter", section: "31", title: "Distributed Database Concepts", anchor: "ADMIN028", file: "ds_concepts.htm" },
  { topic: "chapter", section: "32", title: "Managing a Distributed Database", anchor: "ADMIN029", file: "ds_admin.htm" },
  { topic: "chapter", section: "33", title: "Developing Applications for a Distributed Database System", anchor: "ADMIN030", file: "ds_appdev.htm" },
  { topic: "chapter", section: "34", title: "Distributed Transactions Concepts", anchor: "ADMIN031", file: "ds_txns.htm" },
  { topic: "chapter", section: "35", title: "Managing Distributed Transactions", anchor: "ADMIN032", file: "ds_txnman.htm" },
  { topic: "appendix", section: "A", title: "Support for DBMS_JOB in Oracle Database 11g Release 2", anchor: "ADMIN11002", file: "appendix_a.htm" },
  { } ];
