var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Rules Manager", anchor: "EXPRN001", file: "exprn_intro.htm" },
  { topic: "chapter", section: "2", title: "Rules Manager Concepts", anchor: "EXPRN065", file: "exprn_brm_intro.htm" },
  { topic: "chapter", section: "3", title: "Event Management Policies", anchor: "EXPRN075", file: "exprn_brm_eventpolicies.htm" },
  { topic: "chapter", section: "4", title: "Event and Rule Class Configurations", anchor: "EXPRN472", file: "exprn_brm_evnt_rcconfig.htm" },
  { topic: "chapter", section: "5", title: "Rule Conditions", anchor: "EXPRN4472", file: "exprn_brm_rule_cond.htm" },
  { topic: "chapter", section: "6", title: "Rules Applications That Span Multiple Tiers", anchor: "EXPRN513", file: "exprn_brm_mtier.htm" },
  { topic: "chapter", section: "7", title: "Rules Manager Object Types", anchor: "EXPRN095", file: "exprn_brm_objtypes.htm" },
  { topic: "chapter", section: "8", title: "DBMS_RLMGR Package", anchor: "EXPRN096", file: "exprn_brm_dbmsrlmgr_pkg.htm" },
  { topic: "chapter", section: "9", title: "Rules Manager Views", anchor: "EXPRN097", file: "exprn_brm_views.htm" },
  { topic: "chapter", section: "10", title: "Rules Manager Use Cases", anchor: "EXPRN103", file: "exprn_brm_usecases.htm" },
  { topic: "chapter", section: "11", title: "Oracle Expression Filter Concepts", anchor: "EXPRN007", file: "exprn_expconcepts.htm" },
  { topic: "chapter", section: "12", title: "Indexing Expressions", anchor: "EXPRN018", file: "exprn_indexexpressions.htm" },
  { topic: "chapter", section: "13", title: "Expressions with XPath Predicates", anchor: "EXPRN027", file: "exprn_xpathpredicates.htm" },
  { topic: "chapter", section: "14", title: "Expressions with Spatial and Text Predicates", anchor: "EXPRN481", file: "exprn_spatialpred.htm" },
  { topic: "chapter", section: "15", title: "SQL Operators and Statements", anchor: "EXPRN045", file: "exprn_sql.htm" },
  { topic: "chapter", section: "16", title: "Using Expression Filter with Utilities", anchor: "EXPRN039", file: "exprn_utilities.htm" },
  { topic: "chapter", section: "17", title: "Object Types", anchor: "EXPRN051", file: "exprn_types.htm" },
  { topic: "chapter", section: "18", title: "Management Procedures Using the DBMS_EXPFIL Package", anchor: "EXPRN052", file: "exprn_packages.htm" },
  { topic: "chapter", section: "19", title: "Expression Filter Views", anchor: "EXPRN053", file: "exprn_views.htm" },
  { topic: "appendix", section: "A", title: "Managing Expressions Defined on One or More Database Tables", anchor: "EXPRN111", file: "exprn_app_a.htm" },
  { topic: "appendix", section: "B", title: "Application Examples", anchor: "EXPRN112", file: "exprn_app_b.htm" },
  { topic: "appendix", section: "C", title: "Internal Objects", anchor: "EXPRN560", file: "exprn_app_c.htm" },
  { topic: "appendix", section: "D", title: "Converting Rules Applications", anchor: "EXPRN562", file: "exprn_app_d.htm" },
  { topic: "appendix", section: "E", title: "Installing Rules Manager and Expression Filter", anchor: "EXPRN113", file: "exprn_app_e.htm" },
  { topic: "appendix", section: "F", title: "XML Schemas", anchor: "EXPRN114", file: "exprn_app_f.htm" },
  { topic: "appendix", section: "G", title: "Implementing Various Forms of Rule Actions With the Action Callback Procedure", anchor: "EXPRN566", file: "exprn_app_g.htm" },
  { } ];
