var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Advanced Security", anchor: "ASOAG010", file: "asointro.htm" },
  { topic: "chapter", section: "2", title: "Configuration and Administration Tools Overview", anchor: "ASOAG002", file: "asotools.htm" },
  { topic: "chapter", section: "3", title: "Introduction to Oracle Data Redaction", anchor: "ASOAG594", file: "redaction.htm" },
  { topic: "chapter", section: "4", title: "Oracle Data Redaction Features and Capabilities", anchor: "ASOAG10643", file: "redaction_features.htm" },
  { topic: "chapter", section: "5", title: "Configuring Oracle Data Redaction Policies", anchor: "ASOAG10490", file: "redaction_config.htm" },
  { topic: "chapter", section: "6", title: "Oracle Data Redaction Use with Oracle\u00A0Database\u00A0Features", anchor: "ASOAG10491", file: "redaction_other.htm" },
  { topic: "chapter", section: "7", title: "Security Guidelines for Oracle Data Redaction", anchor: "ASOAG10498", file: "redaction_guidelines.htm" },
  { topic: "chapter", section: "8", title: "Securing Stored Data Using Transparent\u00A0Data\u00A0Encryption", anchor: "ASOAG600", file: "asotrans.htm" },
  { topic: "chapter", section: "9", title: "Configuring Network Data Encryption and\u00A0Integrity for Oracle Servers and Clients", anchor: "ASOAG020", file: "asoconfg.htm" },
  { topic: "chapter", section: "10", title: "Configuring Network Authentication, Encryption, and Integrity for Thin JDBC Clients", anchor: "ASOAG030", file: "asojbdc.htm" },
  { topic: "chapter", section: "11", title: "Configuring RADIUS Authentication", anchor: "ASOAG040", file: "asoradus.htm" },
  { topic: "chapter", section: "12", title: "Configuring Kerberos Authentication", anchor: "ASOAG060", file: "asokerb.htm" },
  { topic: "chapter", section: "13", title: "Configuring Secure Sockets Layer Authentication", anchor: "ASOAG070", file: "asossl.htm" },
  { topic: "chapter", section: "14", title: "Using Oracle Wallet Manager", anchor: "ASOAG160", file: "asowalet.htm" },
  { topic: "chapter", section: "15", title: "Configuring Multiple Authentication Methods and Disabling Oracle Advanced Security", anchor: "ASOAG090", file: "asoauth.htm" },
  { topic: "appendix", section: "A", title: "Data Encryption and Integrity Parameters", anchor: "ASOAG901", file: "asoappa.htm" },
  { topic: "appendix", section: "B", title: "Authentication Parameters", anchor: "ASOAG911", file: "asoappb.htm" },
  { topic: "appendix", section: "C", title: "Integrating Authentication Devices Using\u00A0RADIUS", anchor: "ASOAG921", file: "asoappc.htm" },
  { topic: "appendix", section: "D", title: "Oracle Advanced Security FIPS 140 Settings", anchor: "ASOAG9825", file: "asoappe.htm" },
  { topic: "appendix", section: "E", title: "orapki Utility", anchor: "ASOAG500", file: "asoappf.htm" },
  { topic: "appendix", section: "F", title: "Entrust-Enabled Secure Sockets Layer Authentication", anchor: "ASOAG080", file: "asoappg.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "ASOAG10265", file: "asogls.htm" },
  { } ];
