var chapters = [
  { topic: "chapter", section: "1", title: "Introducing Oracle Communications Data Model", anchor: "CDMRF110", file: "intro_cdm.htm" },
  { topic: "chapter", section: "2", title: "Logical Data Model Foundation", anchor: "CDMRF118", file: "logical_cdm2.htm" },
  { topic: "chapter", section: "3", title: "Logical Data Model Dimensions", anchor: "CDMRF195", file: "dimensional.htm" },
  { topic: "chapter", section: "4", title: "Oracle Communications Data Model Physical Data Model", anchor: "CDMRF717", file: "physical_cdm.htm" },
  { topic: "chapter", section: "5", title: "Oracle Communications Data Model Logical to Physical Mapping", anchor: "CDMRF739", file: "logical_physical_cdm.htm" },
  { topic: "chapter", section: "6", title: "Oracle Communications Data Model Partitioning", anchor: "CDMRF1442", file: "physical_partitions_cdm.htm" },
  { topic: "chapter", section: "7", title: "Oracle Communications Data Model Intra-ETL", anchor: "CDMRF743", file: "etl_cdm.htm" },
  { topic: "chapter", section: "8", title: "Oracle Communications Data Model OLAP Model Dimensions", anchor: "CDMRF840", file: "olap_cdm.htm" },
  { topic: "chapter", section: "9", title: "Oracle Communications Data Model OLAP Model Cubes", anchor: "CDMRF1241", file: "olap_cubes_cdm.htm" },
  { topic: "chapter", section: "10", title: "Oracle Communications Data Model Data Mining Models", anchor: "CDMRF1188", file: "data_mining_cdm.htm" },
  { topic: "chapter", section: "11", title: "Oracle Communications Data Model Utility Scripts", anchor: "CDMRF1227", file: "utility_scripts_cdm.htm" },
  { topic: "chapter", section: "12", title: "Oracle Communications Data Model Reports", anchor: "CDMRF1242", file: "sample_reports.htm" },
  { topic: "appendix", section: "A", title: "Control Tables", anchor: "CDMRF1445", file: "control_cdm.htm" },
  { topic: "appendix", section: "B", title: "Oracle Communications Data Model Business Use Case", anchor: "CDMRF1460", file: "app_buc2.htm" },
  { topic: "appendix", section: "C", title: "Oracle Communications Data Model Assumptions", anchor: "CDMRF2080", file: "app_assumption.htm" },
  { topic: "appendix", section: "D", title: "Physical Table and Logical Data Model Changes for Release 11.3.2", anchor: "CDMRF2105", file: "app_rel1132.htm" },
  { } ];
