var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Data Cartridges", anchor: "ADDCI110", file: "introduction.htm" },
  { topic: "chapter", section: "2", title: "Roadmap to Building a Data Cartridge", anchor: "ADDCI120", file: "roadmap.htm" },
  { topic: "chapter", section: "3", title: "Defining Object Types", anchor: "ADDCI210", file: "obj_types.htm" },
  { topic: "chapter", section: "4", title: "Implementing Data Cartridges in PL/SQL", anchor: "ADDCI240", file: "pl_sql.htm" },
  { topic: "chapter", section: "5", title: "Implementing Data Cartridges in C, C++, and Java", anchor: "ADDCI250", file: "c_cpp_java.htm" },
  { topic: "chapter", section: "6", title: "Working with Multimedia Data Types", anchor: "ADDCI260", file: "lobs.htm" },
  { topic: "chapter", section: "7", title: "Using Extensible Indexing", anchor: "ADDCI270", file: "ext_idx_frmwork.htm" },
  { topic: "chapter", section: "8", title: "Building Domain Indexes", anchor: "ADDCI290", file: "dom_idx.htm" },
  { topic: "chapter", section: "9", title: "Defining Operators", anchor: "ADDCI2100", file: "operators.htm" },
  { topic: "chapter", section: "10", title: "Using Extensible Optimizer", anchor: "ADDCI2110", file: "ext_optimizer.htm" },
  { topic: "chapter", section: "11", title: "Using User-Defined Aggregate Functions", anchor: "ADDCI2120", file: "aggr_functions.htm" },
  { topic: "chapter", section: "12", title: "Using Cartridge Services", anchor: "ADDCI2130", file: "cart_services.htm" },
  { topic: "chapter", section: "13", title: "Using Pipelined and Parallel Table Functions", anchor: "ADDCI2140", file: "pipe_paral_tbl.htm" },
  { topic: "chapter", section: "14", title: "Designing Data Cartridges", anchor: "ADDCI2150", file: "cart_design.htm" },
  { topic: "chapter", section: "15", title: "Power Demand Cartridge Example", anchor: "ADDCI3150", file: "pwr_example.htm" },
  { topic: "chapter", section: "16", title: "PSBTREE: Extensible Indexing Example", anchor: "ADDCI3160", file: "psbtree_example.htm" },
  { topic: "chapter", section: "17", title: "Pipelined Table Functions: Interface Approach Example", anchor: "ADDCI3170", file: "pipelined_example.htm" },
  { topic: "chapter", section: "18", title: "Cartridge Services Using C, C++ and Java", anchor: "ADDCI4180", file: "serv_c_java_ref.htm" },
  { topic: "chapter", section: "19", title: "Extensibility Constants, Types, and Mappings", anchor: "ADDCI4190", file: "ext_types_ref.htm" },
  { topic: "chapter", section: "20", title: "Extensible Indexing Interface", anchor: "ADDCI4200", file: "ext_idx_ref.htm" },
  { topic: "chapter", section: "21", title: "Extensible Optimizer Interface", anchor: "ADDCI4210", file: "ext_opt_ref.htm" },
  { topic: "chapter", section: "22", title: "User-Defined Aggregate Functions Interface", anchor: "ADDCI4220", file: "ext_agg_ref.htm" },
  { topic: "chapter", section: "23", title: "Pipelined and Parallel Table Functions", anchor: "ADDCI4230", file: "pipe_paral_tbl_ref.htm" },
  { topic: "appendix", section: "A", title: "User-Managed Local Domain Indexes", anchor: "ADDCI5162", file: "user_man_idx_apnd.htm" },
  { } ];
