var chapters = [
  { topic: "chapter", section: "1", title: "Administering Oracle Database 11g", anchor: "VMSAR332", file: "ch1.htm" },
  { topic: "chapter", section: "2", title: "Starting and Stopping Oracle Software", anchor: "VMSAR368", file: "ch2.htm" },
  { topic: "chapter", section: "3", title: "Configuring Oracle Products", anchor: "VMSAR391", file: "ch3.htm" },
  { topic: "chapter", section: "4", title: "Administering SQL*Plus", anchor: "VMSAR399", file: "ch4.htm" },
  { topic: "chapter", section: "5", title: "Configuring Oracle Net Services", anchor: "VMSAR420", file: "ch5.htm" },
  { topic: "chapter", section: "6", title: "Using Oracle Precompilers and the Oracle Call Interface", anchor: "VMSAR475", file: "ch6.htm" },
  { topic: "chapter", section: "7", title: "Building and Running Demonstrations", anchor: "VMSAR542", file: "ch7.htm" },
  { topic: "chapter", section: "8", title: "Tuning Oracle Database 11g", anchor: "VMSAR575", file: "ch8.htm" },
  { topic: "appendix", section: "A", title: "Database Limits", anchor: "VMSAR592", file: "apa.htm" },
  { topic: "appendix", section: "B", title: "Managing the Database", anchor: "VMSAR596", file: "apb.htm" },
  { topic: "appendix", section: "C", title: "Backing Up and Archiving the Database", anchor: "VMSAR609", file: "apc.htm" },
  { topic: "appendix", section: "D", title: "Logical Names and Parameters", anchor: "VMSAR630", file: "apd.htm" },
  { topic: "appendix", section: "E", title: "Messages and Codes", anchor: "VMSAR676", file: "ape.htm" },
  { topic: "appendix", section: "F", title: "Process Control", anchor: "VMSAR677", file: "apf.htm" },
  { } ];
