var chapters = [
  { topic: "chapter", section: "1", title: "What Is Data Mining?", anchor: "DMCON002", file: "process.htm" },
  { topic: "chapter", section: "2", title: "Introducing Oracle Data Mining", anchor: "DMCON001", file: "intro_concepts.htm" },
  { topic: "chapter", section: "3", title: "Introducing Oracle Predictive Analytics", anchor: "DMCON012", file: "pa_dmcon.htm" },
  { topic: "chapter", section: "4", title: "Regression", anchor: "DMCON005", file: "regress.htm" },
  { topic: "chapter", section: "5", title: "Classification", anchor: "DMCON004", file: "classify.htm" },
  { topic: "chapter", section: "6", title: "Anomaly Detection", anchor: "DMCON006", file: "anomalies.htm" },
  { topic: "chapter", section: "7", title: "Clustering", anchor: "DMCON008", file: "clustering.htm" },
  { topic: "chapter", section: "8", title: "Association", anchor: "DMCON009", file: "market_basket.htm" },
  { topic: "chapter", section: "9", title: "Feature Selection and Extraction", anchor: "DMCON010", file: "feature_extr.htm" },
  { topic: "chapter", section: "10", title: "Apriori", anchor: "DMCON061", file: "algo_apriori.htm" },
  { topic: "chapter", section: "11", title: "Decision Tree", anchor: "DMCON019", file: "algo_decisiontree.htm" },
  { topic: "chapter", section: "12", title: "Generalized Linear Models", anchor: "DMCON022", file: "algo_glm.htm" },
  { topic: "chapter", section: "13", title: "k-Means", anchor: "DMCON057", file: "algo_kmeans.htm" },
  { topic: "chapter", section: "14", title: "Minimum Description Length", anchor: "DMCON340", file: "algo_mdl.htm" },
  { topic: "chapter", section: "15", title: "Naive Bayes", anchor: "DMCON018", file: "algo_nb.htm" },
  { topic: "chapter", section: "16", title: "Non-Negative Matrix Factorization", anchor: "DMCON058", file: "algo_nmf.htm" },
  { topic: "chapter", section: "17", title: "O-Cluster", anchor: "DMCON059", file: "algo_oc.htm" },
  { topic: "chapter", section: "18", title: "Support Vector Machines", anchor: "DMCON025", file: "algo_svm.htm" },
  { topic: "chapter", section: "19", title: "Automatic and Embedded Data Preparation", anchor: "DMCON003", file: "xform_data.htm" },
  { topic: "chapter", section: "20", title: "Text Mining", anchor: "DMCON011", file: "text.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "DMCON013", file: "glossary.htm" },
  { } ];
