var chapters = [
  { topic: "chapter", section: "1", title: "Designing Source and Target Schemas", anchor: "WBETL01000", file: "design_tgt_schemas.htm" },
  { topic: "chapter", section: "2", title: "Creating Relational Data Objects", anchor: "WBETL02000", file: "orcl_data_objx.htm" },
  { topic: "chapter", section: "3", title: "Defining Dimensional Objects", anchor: "WBETL03000", file: "dim_objects.htm" },
  { topic: "chapter", section: "4", title: "Overview of Transforming Data", anchor: "WBETL04000", file: "transformdata_intro.htm" },
  { topic: "chapter", section: "5", title: "Creating PL/SQL Mappings", anchor: "WBETL05000", file: "mappings.htm" },
  { topic: "chapter", section: "6", title: "Performing ETL Using Dimensional Objects", anchor: "WBETL06000", file: "dim_mappings.htm" },
  { topic: "chapter", section: "7", title: "Using SQL*Loader, SAP, and Code Template Mappings", anchor: "WBETL07000", file: "sap_km_mappings.htm" },
  { topic: "chapter", section: "8", title: "Designing Process Flows", anchor: "WBETL08000", file: "design_processflows.htm" },
  { topic: "chapter", section: "9", title: "Defining Custom Transformations", anchor: "WBETL09000", file: "custom_transforms.htm" },
  { topic: "chapter", section: "10", title: "Understanding Performance and Advanced ETL Concepts", anchor: "WBETL10000", file: "etl_performance.htm" },
  { topic: "chapter", section: "11", title: "Scheduling ETL Jobs", anchor: "WBETL11000", file: "scheduling_etl.htm" },
  { topic: "chapter", section: "12", title: "Deploying to Target Schemas and Executing ETL Logic", anchor: "WBETL12000", file: "deploy.htm" },
  { topic: "chapter", section: "13", title: "Auditing Deployments and Executions", anchor: "WBETL13000", file: "auditing.htm" },
  { topic: "chapter", section: "14", title: "Managing Metadata Dependencies", anchor: "WBETL14000", file: "lineage_impact_mdm.htm" },
  { topic: "chapter", section: "15", title: "Troubleshooting and Error Handling for ETL Designs", anchor: "WBETL15000", file: "errors_trouble.htm" },
  { topic: "chapter", section: "16", title: "Creating and Consuming Web Services in Oracle Warehouse Builder", anchor: "WBETL16000", file: "design_webservices.htm" },
  { topic: "chapter", section: "17", title: "Moving Large Volumes of Data Using Transportable Modules", anchor: "WBETL17000", file: "trans_mod.htm" },
  { topic: "chapter", section: "18", title: "Performing Data Profiling", anchor: "WBETL18000", file: "data_profiling.htm" },
  { topic: "chapter", section: "19", title: "Designing and Deriving Data Rules", anchor: "WBETL19000", file: "data_rules.htm" },
  { topic: "chapter", section: "20", title: "Monitoring Quality with Data Auditors and Data Rules", anchor: "WBETL20000", file: "data_auditors.htm" },
  { topic: "chapter", section: "21", title: "Data Cleansing and Correction with Data Rules", anchor: "WBETL21000", file: "data_cleansing.htm" },
  { topic: "chapter", section: "22", title: "Name and Address Cleansing", anchor: "WBETL22000", file: "name_address.htm" },
  { topic: "chapter", section: "23", title: "Matching, Merging, and Deduplication", anchor: "WBETL23000", file: "match_merge.htm" },
  { topic: "chapter", section: "24", title: "Mappings and Process Flows Reference", anchor: "WBETL24000", file: "ref_maps_processflows.htm" },
  { topic: "chapter", section: "25", title: "Source and Target Operators", anchor: "WBETL25000", file: "src_tgt_opers.htm" },
  { topic: "chapter", section: "26", title: "Data Flow Operators", anchor: "WBETL26000", file: "data_flow_opers.htm" },
  { topic: "chapter", section: "27", title: "Activities in Process Flows", anchor: "WBETL27000", file: "activities_in_pf.htm" },
  { topic: "chapter", section: "28", title: "Oracle Warehouse BuilderTransformations Reference", anchor: "WBETL28000", file: "ref_sqltransforms.htm" },
  { topic: "chapter", section: "29", title: "Oracle Warehouse Builder Code Template Tools and Substitution Methods Reference", anchor: "CJAJAIDF", file: "code_tempates.htm" },
  { } ];
