var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Data Guard", anchor: "SBYDB00010", file: "concepts.htm" },
  { topic: "chapter", section: "2", title: "Getting Started with Data Guard", anchor: "SBYDB00100", file: "standby.htm" },
  { topic: "chapter", section: "3", title: "Creating a Physical Standby Database", anchor: "SBYDB00200", file: "create_ps.htm" },
  { topic: "chapter", section: "4", title: "Creating a Logical Standby Database", anchor: "SBYDB00300", file: "create_ls.htm" },
  { topic: "chapter", section: "5", title: "Data Guard Protection Modes", anchor: "SBYDB02000", file: "protection.htm" },
  { topic: "chapter", section: "6", title: "Redo Transport Services", anchor: "SBYDB00400", file: "log_transport.htm" },
  { topic: "chapter", section: "7", title: "Apply Services", anchor: "SBYDB00500", file: "log_apply.htm" },
  { topic: "chapter", section: "8", title: "Role Transitions", anchor: "SBYDB00600", file: "role_management.htm" },
  { topic: "chapter", section: "9", title: "Managing Physical and Snapshot Standby Databases", anchor: "SBYDB00700", file: "manage_ps.htm" },
  { topic: "chapter", section: "10", title: "Managing a Logical Standby Database", anchor: "SBYDB00800", file: "manage_ls.htm" },
  { topic: "chapter", section: "11", title: "Using RMAN to Back Up and Restore Files", anchor: "SBYDB04700", file: "rman.htm" },
  { topic: "chapter", section: "12", title: "Using SQL Apply to Upgrade the Oracle Database", anchor: "SBYDB00830", file: "rollup.htm" },
  { topic: "chapter", section: "13", title: "Data Guard Scenarios", anchor: "SBYDB00900", file: "scenarios.htm" },
  { topic: "chapter", section: "14", title: "Initialization Parameters", anchor: "SBYDB4901", file: "init_params.htm" },
  { topic: "chapter", section: "15", title: "LOG_ARCHIVE_DEST_n Parameter Attributes", anchor: "SBYDB01100", file: "log_arch_dest_param.htm" },
  { topic: "chapter", section: "16", title: "SQL Statements Relevant to Data Guard", anchor: "SBYDB01222", file: "sql_stmts.htm" },
  { topic: "chapter", section: "17", title: "Views Relevant to Oracle Data Guard", anchor: "SBYDB01300", file: "views.htm" },
  { topic: "appendix", section: "A", title: "Troubleshooting Data Guard", anchor: "SBYDB01400", file: "troubleshooting.htm" },
  { topic: "appendix", section: "B", title: "Upgrading and Downgrading Databases in a Data Guard Configuration", anchor: "SBYDB1200", file: "upgrades.htm" },
  { topic: "appendix", section: "C", title: "Data Type and DDL Support on a Logical Standby Database", anchor: "SBYDB00305", file: "data_support.htm" },
  { topic: "appendix", section: "D", title: "Data Guard and Oracle Real Application Clusters", anchor: "SBYDB01700", file: "rac_support.htm" },
  { topic: "appendix", section: "E", title: "Creating a Standby Database with Recovery Manager", anchor: "SBYDB01500", file: "rcmbackp.htm" },
  { topic: "appendix", section: "F", title: "Setting Archive Tracing", anchor: "SBYDB01880", file: "trace.htm" },
  { } ];
