var chapters = [
  { topic: "chapter", section: "1", title: "Getting Acquainted", anchor: "BABFIEEH", file: "ch_one.htm" },
  { topic: "chapter", section: "2", title: "Learning the Basics", anchor: "BABBHAGG", file: "ch_two.htm" },
  { topic: "chapter", section: "3", title: "Meeting Program Requirements", anchor: "BABCBCDA", file: "ch_three.htm" },
  { topic: "chapter", section: "4", title: "\u00A0Using Embedded SQL", anchor: "BABEGAEG", file: "ch_four.htm" },
  { topic: "chapter", section: "5", title: "Using Embedded PL/SQL", anchor: "BIHJJIBA", file: "ch_five.htm" },
  { topic: "chapter", section: "6", title: "Running the Oracle Precompilers", anchor: "BABDDACC", file: "ch_six.htm" },
  { topic: "chapter", section: "7", title: "Defining and Controlling Transactions", anchor: "BABIFBDG", file: "ch_seven.htm" },
  { topic: "chapter", section: "8", title: "Error Handling and Diagnostics", anchor: "BABJDJGJ", file: "ch_eight.htm" },
  { topic: "chapter", section: "9", title: "Using Host Arrays", anchor: "BABHFECC", file: "ch_nine.htm" },
  { topic: "chapter", section: "10", title: "Using Dynamic SQL", anchor: "CHDEFGBC", file: "ch_ten.htm" },
  { topic: "chapter", section: "11", title: "Writing User Exits", anchor: "CHDGFJHF", file: "ch_eleven.htm" },
  { topic: "appendix", section: "A", title: "New Features", anchor: "BABGEEIJ", file: "appa.htm" },
  { topic: "appendix", section: "B", title: "Oracle Reserved Words, Keywords, and Namespaces", anchor: "CJHIIICD", file: "appb.htm" },
  { topic: "appendix", section: "C", title: "Performance Tuning", anchor: "BABCHGDI", file: "appc.htm" },
  { topic: "appendix", section: "D", title: "Syntactic and Semantic Checking", anchor: "BABFFIIF", file: "appd.htm" },
  { topic: "appendix", section: "E", title: "Embedded SQL Commands and Directives", anchor: "CJHGHJHG", file: "appe.htm" },
  { } ];
