var chapters = [
  { topic: "chapter", section: "1", title: "Introducing Oracle Data Provider for .NET", anchor: "ODPNT0005", file: "intro.htm" },
  { topic: "chapter", section: "2", title: "Installing and Configuring Oracle Data Provider for .NET", anchor: "ODPNT0006", file: "install.htm" },
  { topic: "chapter", section: "3", title: "Features of Oracle Data Provider for .NET", anchor: "ODPNT0007", file: "features.htm" },
  { topic: "chapter", section: "4", title: "Oracle Data Provider for .NETServer-Side Features", anchor: "ODPNT0017", file: "extensions.htm" },
  { topic: "chapter", section: "5", title: "Oracle Data Provider for .NET Classes", anchor: "ODPNT0008", file: "client.htm" },
  { topic: "chapter", section: "6", title: "Oracle Data Provider for .NET XML-Related Classes", anchor: "ODPNT0010", file: "xmlclass.htm" },
  { topic: "chapter", section: "7", title: "ADO.NET 2.0 Classes", anchor: "ODPNT2585", file: "adonet20.htm" },
  { topic: "chapter", section: "8", title: "Oracle Data Provider for .NET HA Event Classes", anchor: "ODPNT2809", file: "haevent.htm" },
  { topic: "chapter", section: "9", title: "Database Change Notification", anchor: "ODPNT0011", file: "changenote.htm" },
  { topic: "chapter", section: "10", title: "Oracle Data Provider for .NET Globalization Classes", anchor: "ODPNT0012", file: "global.htm" },
  { topic: "chapter", section: "11", title: "Oracle Data Provider for .NET Failover Classes", anchor: "ODPNT0013", file: "failov.htm" },
  { topic: "chapter", section: "12", title: "Advanced Queuing Support", anchor: "ODPNT3236", file: "aq.htm" },
  { topic: "chapter", section: "13", title: "Oracle Data Provider for .NET Types\u00A0Classes", anchor: "ODPNT0014", file: "typeobjs.htm" },
  { topic: "chapter", section: "14", title: "Oracle Data Provider for .NET Types Structures", anchor: "ODPNT0009", file: "oratypes.htm" },
  { topic: "chapter", section: "15", title: "Oracle Data Provider for .NET Types Exceptions", anchor: "ODPNT0015", file: "typeexcep.htm" },
  { topic: "chapter", section: "16", title: "Oracle Data Provider for .NET UDT-Related Classes", anchor: "ODPNT0022", file: "objects.htm" },
  { topic: "chapter", section: "17", title: "Oracle Data Provider for .NET Bulk Copy Classes", anchor: "ODPNT0021", file: "bulkcopy.htm" },
  { topic: "appendix", section: "A", title: "Oracle Schema Collections", anchor: "ODPNT7724", file: "appendix.htm" },
  { topic: "appendix", section: "B", title: "Mapping LINQ Canonical Functions and Oracle Functions", anchor: "ODPNT7777", file: "canonical_map.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "ODPNT7784", file: "glossary.htm" },
  { } ];
