var chapters = [
  { topic: "chapter", section: "1", title: "Introduction to Oracle Automatic Storage Management", anchor: "OSTMG036", file: "asmcon.htm" },
  { topic: "chapter", section: "2", title: "Considerations for Oracle ASM Storage", anchor: "OSTMG11000", file: "asmprepare.htm" },
  { topic: "chapter", section: "3", title: "Administering Oracle ASM Instances", anchor: "OSTMG136", file: "asminst.htm" },
  { topic: "chapter", section: "4", title: "Administering Oracle ASM Disk Groups", anchor: "OSTMG137", file: "asmdiskgrps.htm" },
  { topic: "chapter", section: "5", title: "Introduction to Oracle ACFS", anchor: "OSTMG30000", file: "asmfilesystem.htm" },
  { topic: "chapter", section: "6", title: "Using Views to Display Information", anchor: "OSTMG10030", file: "asmviews.htm" },
  { topic: "chapter", section: "7", title: "Administering Oracle ASM Files, Directories, and Templates", anchor: "OSTMG139", file: "asmfiles.htm" },
  { topic: "chapter", section: "8", title: "Performing Oracle ASM Data Migration with RMAN", anchor: "OSTMG12000", file: "asm_rman.htm" },
  { topic: "chapter", section: "9", title: "Administering Oracle ASM with Oracle Enterprise Manager", anchor: "OSTMG2000", file: "asm_em.htm" },
  { topic: "chapter", section: "10", title: "Administering Oracle ACFS with Oracle Enterprise Manager", anchor: "OSTMG40000", file: "asmfs_em.htm" },
  { topic: "chapter", section: "11", title: "Oracle ASM Configuration Assistant", anchor: "OSTMG50000", file: "asmca.htm" },
  { topic: "chapter", section: "12", title: "Oracle ASM Command-Line Utility", anchor: "OSTMG016", file: "asm_util.htm" },
  { topic: "chapter", section: "13", title: "Oracle ACFS Command-Line Tools", anchor: "OSTMG90000", file: "asmfs_util.htm" },
  { topic: "appendix", section: "A", title: "Creating Database Files in Oracle ASM Using SQL*Plus", anchor: "OSTMG1390", file: "asmbysql.htm" },
  { topic: "appendix", section: "B", title: "Oracle ACFS Advanced Topics", anchor: "OSTMG35000", file: "asmfs_extra.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "OSTMG95298", file: "ostmg_gloss.htm" },
  { } ];
