var chapters = [
  { topic: "chapter", section: "1", title: "Overview of Oracle Data Pump", anchor: "SUTIL100", file: "dp_overview.htm" },
  { topic: "chapter", section: "2", title: "Data Pump Export", anchor: "SUTIL200", file: "dp_export.htm" },
  { topic: "chapter", section: "3", title: "Data Pump Import", anchor: "SUTIL300", file: "dp_import.htm" },
  { topic: "chapter", section: "4", title: "Data Pump Legacy Mode", anchor: "SUTIL959", file: "dp_legacy.htm" },
  { topic: "chapter", section: "5", title: "Data Pump Performance", anchor: "SUTIL400", file: "dp_perf.htm" },
  { topic: "chapter", section: "6", title: "The Data Pump API", anchor: "SUTIL600", file: "dp_api.htm" },
  { topic: "chapter", section: "7", title: "SQL*Loader Concepts", anchor: "SUTIL003", file: "ldr_concepts.htm" },
  { topic: "chapter", section: "8", title: "SQL*Loader Command-Line Reference", anchor: "SUTIL004", file: "ldr_params.htm" },
  { topic: "chapter", section: "9", title: "SQL*Loader Control File Reference", anchor: "SUTIL005", file: "ldr_control_file.htm" },
  { topic: "chapter", section: "10", title: "SQL*Loader Field List Reference", anchor: "SUTIL006", file: "ldr_field_list.htm" },
  { topic: "chapter", section: "11", title: "Loading Objects, LOBs, and Collections", anchor: "SUTIL007", file: "ldr_loading.htm" },
  { topic: "chapter", section: "12", title: "Conventional and Direct Path Loads", anchor: "SUTIL009", file: "ldr_modes.htm" },
  { topic: "chapter", section: "13", title: "External Tables Concepts", anchor: "SUTIL011", file: "et_concepts.htm" },
  { topic: "chapter", section: "14", title: "The ORACLE_LOADER Access Driver", anchor: "SUTIL012", file: "et_params.htm" },
  { topic: "chapter", section: "15", title: "The ORACLE_DATAPUMP Access Driver", anchor: "SUTIL500", file: "et_dp_driver.htm" },
  { topic: "chapter", section: "16", title: "ADRCI: ADR Command Interpreter", anchor: "SUTIL700", file: "adrci.htm" },
  { topic: "chapter", section: "17", title: "DBVERIFY: Offline Database Verification Utility", anchor: "SUTIL013", file: "dbverify.htm" },
  { topic: "chapter", section: "18", title: "DBNEWID Utility", anchor: "SUTIL014", file: "dbnewid.htm" },
  { topic: "chapter", section: "19", title: "Using LogMiner to Analyze Redo Log Files", anchor: "SUTIL019", file: "logminer.htm" },
  { topic: "chapter", section: "20", title: "Using the Metadata APIs", anchor: "SUTIL015", file: "metadata_api.htm" },
  { topic: "chapter", section: "21", title: "Original Export", anchor: "SUTIL3634", file: "original_export.htm" },
  { topic: "chapter", section: "22", title: "Original Import", anchor: "SUTIL001", file: "original_import.htm" },
  { topic: "appendix", section: "A", title: "SQL*Loader Syntax Diagrams", anchor: "SUTIL050", file: "app_ldr_syntax.htm" },
  { } ];
