var chapters = [
  { topic: "chapter", section: "1", title: "Preinstallation Checklist", anchor: "RIWIN961", file: "chklist.htm" },
  { topic: "chapter", section: "2", title: "Installing Oracle Database 11g with Oracle Real Application Clusters", anchor: "RIWIN1007", file: "racinstl.htm" },
  { topic: "chapter", section: "3", title: "Creating Oracle Real Application Clusters Databases with Oracle Database Configuration Assistant", anchor: "RIWIN004", file: "dbcacrea.htm" },
  { topic: "chapter", section: "4", title: "Oracle Real Application Clusters Postinstallation Procedures", anchor: "BABHHEHG", file: "postinst.htm" },
  { topic: "chapter", section: "5", title: "		Configuring the Server Parameter File in Oracle Real Application Clusters Environments", anchor: "RIWIN007", file: "params.htm" },
  { topic: "chapter", section: "6", title: "Configuring Server Pools and Oracle Enterprise Manager Database Control", anchor: "RIWIN1035", file: "srvpool.htm" },
  { topic: "chapter", section: "7", title: "Understanding the Oracle Real Application Clusters Installed Configuration", anchor: "RIWIN006", file: "undrstnd.htm" },
  { topic: "chapter", section: "8", title: "Removing Oracle Real Application Clusters Software", anchor: "RIWIN1069", file: "rem_orcl.htm" },
  { topic: "appendix", section: "A", title: "Troubleshooting Oracle Real Application Clusters Installations", anchor: "RIWIN1076", file: "trouble.htm" },
  { topic: "appendix", section: "B", title: "		Using Scripts or Response Files to Create Oracle Real Application Clusters Databases", anchor: "RIWIN1085", file: "scripts.htm" },
  { topic: "appendix", section: "C", title: "Converting to Oracle RAC and Oracle RAC One Node from Single-Instance Oracle Databases", anchor: "RIWIN1106", file: "cvrt2rac.htm" },
  { topic: "appendix", section: "D", title: "Directory Structure for Oracle Real Application Clusters Environments", anchor: "RIWIN009", file: "apa.htm" },
  { topic: "appendix", section: "E", title: "How to Stop Processes in an Existing Oracle Real Application Clusters Database", anchor: "RIWIN1135", file: "procstop.htm" },
  { topic: "appendix", section: "F", title: "Managing Oracle Database Port Numbers", anchor: "RIWIN1141", file: "ports.htm" },
  { topic: "appendix", section: "G", title: "Oracle Enterprise Manager Configuration Assistant Reference", anchor: "CEGGFJHB", file: "emca_ref_new.htm" },
  { } ];
