var chapters = [
  { topic: "chapter", section: "1", title: "	 Introduction to Backup and Recovery", anchor: "BRADV8001", file: "rcmintro.htm" },
  { topic: "chapter", section: "2", title: "Getting Started with RMAN", anchor: "BRADV89346", file: "rcmquick.htm" },
  { topic: "chapter", section: "3", title: "Recovery Manager Architecture", anchor: "BRADV001", file: "rcmarchi.htm" },
  { topic: "chapter", section: "4", title: "Starting and Interacting with the RMAN\u00A0Client", anchor: "BRADV005", file: "rcmcnctg.htm" },
  { topic: "chapter", section: "5", title: "Configuring the RMAN Environment", anchor: "BRADV8002", file: "rcmconfb.htm" },
  { topic: "chapter", section: "6", title: "Configuring the RMAN Environment: Advanced Topics", anchor: "BRADV006", file: "rcmconfa.htm" },
  { topic: "chapter", section: "7", title: "Using Flashback Database and Restore Points", anchor: "BRADV71000", file: "flashdb.htm" },
  { topic: "chapter", section: "8", title: "RMAN Backup Concepts", anchor: "BRADV002", file: "rcmcncpt.htm" },
  { topic: "chapter", section: "9", title: "Backing Up the Database", anchor: "BRADV8003", file: "rcmbckba.htm" },
  { topic: "chapter", section: "10", title: "Backing Up the Database: Advanced Topics", anchor: "BRADV007", file: "rcmbckad.htm" },
  { topic: "chapter", section: "11", title: "Reporting on RMAN Operations", anchor: "BRADV8004", file: "rcmreprt.htm" },
  { topic: "chapter", section: "12", title: "Maintaining RMAN Backups and Repository\u00A0Records", anchor: "BRADV8007", file: "rcmmaint.htm" },
  { topic: "chapter", section: "13", title: "Managing a Recovery Catalog", anchor: "BRADV8015", file: "rcmcatdb.htm" },
  { topic: "chapter", section: "14", title: "RMAN Data Repair Concepts", anchor: "BRADV89703", file: "rcmrvcon.htm" },
  { topic: "chapter", section: "15", title: "Diagnosing and Repairing Failures with Data Recovery Advisor", anchor: "BRADV246", file: "rcmrepai.htm" },
  { topic: "chapter", section: "16", title: "Validating Database Files and Backups", anchor: "BRADV90063", file: "rcmvalid.htm" },
  { topic: "chapter", section: "17", title: "Performing Complete Database Recovery", anchor: "BRADV8005", file: "rcmcomre.htm" },
  { topic: "chapter", section: "18", title: "Performing Flashback and Database Point-in-Time Recovery", anchor: "BRADV80055", file: "rcmflash.htm" },
  { topic: "chapter", section: "19", title: "Performing Block Media Recovery", anchor: "BRADV89781", file: "rcmblock.htm" },
  { topic: "chapter", section: "20", title: "Performing RMAN Recovery: Advanced Scenarios", anchor: "BRADV008", file: "rcmadvre.htm" },
  { topic: "chapter", section: "21", title: "Performing RMAN Tablespace Point-in-Time Recovery (TSPITR)", anchor: "BRADV009", file: "rcmtspit.htm" },
  { topic: "chapter", section: "22", title: "Tuning RMAN Performance", anchor: "BRADV011", file: "rcmtunin.htm" },
  { topic: "chapter", section: "23", title: "Troubleshooting RMAN Operations", anchor: "BRADV012", file: "rcmtroub.htm" },
  { topic: "chapter", section: "24", title: "Duplicating a Database", anchor: "BRADV010", file: "rcmdupdb.htm" },
  { topic: "chapter", section: "25", title: "Duplicating a Database: Advanced Topics", anchor: "BRADV441", file: "rcmdupad.htm" },
  { topic: "chapter", section: "26", title: "Creating Transportable Tablespace Sets", anchor: "BRADV05141", file: "rcmttbsb.htm" },
  { topic: "chapter", section: "27", title: "Transporting Data Across Platforms", anchor: "BRADV05432", file: "rcmxplat.htm" },
  { topic: "chapter", section: "28", title: "Making User-Managed Database Backups", anchor: "BRADV016", file: "osbackup.htm" },
  { topic: "chapter", section: "29", title: "Performing User-Managed Database Flashback and Recovery", anchor: "BRADV017", file: "osrecvry.htm" },
  { topic: "chapter", section: "30", title: "Performing User-Managed Recovery: Advanced Scenarios", anchor: "BRADV018", file: "osadvsce.htm" },
  { topic: "glossary", section: "", title: "Glossary", anchor: "BRADV526", file: "glossary.htm" },
  { } ];
