var chapters = [
  { topic: "chapter", section: "1", title: "Using SQL Data Types in Database Applications", anchor: "ADFNS0002", file: "adfns_sqltypes.htm" },
  { topic: "chapter", section: "2", title: "SQL Processing for Application Developers", anchor: "ADFNS007", file: "adfns_sqlproc.htm" },
  { topic: "chapter", section: "3", title: "Using Regular Expressions in Database Applications", anchor: "ADFNS1003", file: "adfns_regexp.htm" },
  { topic: "chapter", section: "4", title: "Using Indexes in Database Applications", anchor: "ADFNS005", file: "adfns_indexes.htm" },
  { topic: "chapter", section: "5", title: "Maintaining Data Integrity in Database Applications", anchor: "ADFNS004", file: "adfns_constraints.htm" },
  { topic: "chapter", section: "6", title: "Coding PL/SQL Subprograms and Packages", anchor: "ADFNS009", file: "adfns_packages.htm" },
  { topic: "chapter", section: "7", title: "Using PL/Scope", anchor: "ADFNS022", file: "adfns_plscope.htm" },
  { topic: "chapter", section: "8", title: "Using the PL/SQL Hierarchical Profiler", anchor: "ADFNS023", file: "adfns_profiler.htm" },
  { topic: "chapter", section: "9", title: "Developing PL/SQL Web Applications", anchor: "ADFNS015", file: "adfns_web.htm" },
  { topic: "chapter", section: "10", title: "Developing PL/SQL Server Pages (PSP)", anchor: "ADFNS016", file: "adfns_psp.htm" },
  { topic: "chapter", section: "11", title: "Using Continuous Query Notification (CQN)", anchor: "ADFNS018", file: "adfns_cqn.htm" },
  { topic: "chapter", section: "12", title: "Using Oracle Flashback Technology", anchor: "ADFNS1008", file: "adfns_flashback.htm" },
  { topic: "chapter", section: "13", title: "Choosing a Programming Environment", anchor: "ADFNS00109", file: "adfns_environments.htm" },
  { topic: "chapter", section: "14", title: "Developing Applications with Multiple Programming Languages", anchor: "ADFNS010", file: "adfns_externproc.htm" },
  { topic: "chapter", section: "15", title: "Developing Applications with Oracle XA", anchor: "ADFNS017", file: "adfns_xa.htm" },
  { topic: "chapter", section: "16", title: "Developing Applications with the Publish-Subscribe Model", anchor: "ADFNS014", file: "adfns_publish.htm" },
  { topic: "chapter", section: "17", title: "Using the Identity Code Package", anchor: "ADFNS019", file: "adfns_idcode.htm" },
  { topic: "chapter", section: "18", title: "Schema Object Dependency", anchor: "ADFNS99967", file: "adfns_dependencies.htm" },
  { topic: "chapter", section: "19", title: "Edition-Based Redefinition", anchor: "ADFNS020", file: "adfns_editions.htm" },
  { topic: "appendix", section: "A", title: "Multithreaded extproc Agent", anchor: "ADFNS00099", file: "adfns_extproc.htm" },
  { } ];
