var chapters = [
  { topic: "chapter", section: "1", title: "OMBALTER to OMBALTER CORRECTION_SCHEMA_ACTION_PLAN", anchor: "", file: "chap1.htm" },
  { topic: "chapter", section: "2", title: "OMBALTER CT to OMBALTER ICONSET", anchor: "", file: "chap2.htm" },
  { topic: "chapter", section: "3", title: "OMBALTER IMPORT_ACTION_PLAN to OMBALTER PLUGGABLE_MAPPING", anchor: "", file: "chap3.htm" },
  { topic: "chapter", section: "4", title: "OMBALTER PLUGGABLE_MAPPING_FOLDER to OMBALTER TRANSPORTABLE_MODULE", anchor: "", file: "chap4.htm" },
  { topic: "chapter", section: "5", title: "OMBALTER UNQUOTED_STRING to OMBCREATE ADVANCED_QUEUE", anchor: "", file: "chap5.htm" },
  { topic: "chapter", section: "6", title: "OMBCREATE ALTERNATIVE_SORT_ORDER to OMBCREATE CUBE", anchor: "", file: "chap6.htm" },
  { topic: "chapter", section: "7", title: "OMBCREATE DATA_AUDITOR to OMBCREATE INTEGRATION_CT", anchor: "", file: "chap7.htm" },
  { topic: "chapter", section: "8", title: "OMBCREATE ITEM_FOLDER to OMBCREATE PLSQL_REF_CURSOR_TYPE", anchor: "", file: "chap8.htm" },
  { topic: "chapter", section: "9", title: "OMBCREATE PLSQL_TABLE_TYPE to OMBCREATE TIME_DIMENSION", anchor: "", file: "chap9.htm" },
  { topic: "chapter", section: "10", title: "OMBCREATE TRANSPORTABLE_MODULE to OMBDESCRIBE MODEL", anchor: "", file: "chap10.htm" },
  { topic: "chapter", section: "11", title: "OMBDISC to OMBDROP CONFIGURATION", anchor: "", file: "chap11.htm" },
  { topic: "chapter", section: "12", title: "OMBDROP CONFIGURATION_TEMPLATE to OMBDROP FLAT_FILE_MODULE", anchor: "", file: "chap12.htm" },
  { topic: "chapter", section: "13", title: "OMBDROP FOLDER to OMBDROP PLATFORM", anchor: "", file: "chap13.htm" },
  { topic: "chapter", section: "14", title: "OMBDROP PLSQL_RECORD_TYPE to OMBDROP TABLE", anchor: "", file: "chap14.htm" },
  { topic: "chapter", section: "15", title: "OMBDROP TABLE_FUNCTION to OMBIMPORT CT_FILE", anchor: "", file: "chap15.htm" },
  { topic: "chapter", section: "16", title: "OMBIMPORT ENTIRE_REPOSITORY MDL_FILE to OMBMENU REMOVE EXPERT", anchor: "", file: "chap16.htm" },
  { topic: "chapter", section: "17", title: "OMBMLSUPDATE to OMBRETRIEVE CATALOG_FOLDER", anchor: "", file: "chap17.htm" },
  { topic: "chapter", section: "18", title: "OMBRETRIEVE CMI_DEFINITION to OMBRETRIEVE DRILL_TO_DETAIL", anchor: "", file: "chap18.htm" },
  { topic: "chapter", section: "19", title: "OMBRETRIEVE EXPERT to OMBRETRIEVE OBIEE_BUSINESS_DEFINITION_MODULE", anchor: "", file: "chap19.htm" },
  { topic: "chapter", section: "20", title: "OMBRETRIEVE OBJECT_TYPE to OMBRETRIEVE REGISTERED_FUNCTION", anchor: "", file: "chap20.htm" },
  { topic: "chapter", section: "21", title: "OMBRETRIEVE ROLE to OMBREVOKE SYS_PRIV", anchor: "", file: "chap21.htm" },
  { topic: "chapter", section: "22", title: "OMBROLLBACK to OMUCOMPILE", anchor: "", file: "chap22.htm" },
  { topic: "chapter", section: "23", title: "OMUCONFIGURE to OMUSTART EXPERT", anchor: "", file: "chap23.htm" },
  { topic: "chapter", section: "24", title: "OMUSTARTJOB to OMUVALIDATE", anchor: "", file: "chap24.htm" },
  { } ];
